/**
 * POST /api/users/create
 *
 * Creates a user in Supabase. Compatible with the existing CreateUserPayload
 * interface used by company/users and superadmin/companies/[orgId]/users pages.
 *
 * Accepts: { displayName, email, password, role, orgId, warehouseId, warehouseIds? }
 * Returns: { ok: true, uid: string }
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/app/_server/db/client";
import { uuidv7 } from "@/app/_server/db/uuidv7";
import {
  hashPassword,
  recordPasswordHistory,
  generateTempPassword,
} from "@/app/_server/auth/password";
import { requireUser } from "@/app/_server/auth/getUser";
import { writeAuditEvent } from "@/app/_server/db/audit";
import { applySecurityHeaders } from "@/app/_server/security/headers";
import { sendMail } from "@/app/_lib/sendMail";
import { emailUserOnboarding } from "@/app/_lib/userEmails";
import type { UserRole } from "@/app/_lib/types";

export interface CreateUserPayload {
  displayName: string;
  email: string;
  password?: string;            // optional — auto-generated when omitted
  role: UserRole;
  orgId: string;
  warehouseId: string;
  warehouseIds?: string[];
}

const ALLOWED_ROLES: UserRole[] = [
  "super_admin",
  "company_admin",
  "guard",
  "wh_manager",
  "regional_manager",
  "cso",
];

export async function POST(req: NextRequest): Promise<NextResponse> {
  let actor;
  try {
    actor = await requireUser(req);
  } catch {
    return applySecurityHeaders(NextResponse.json({ error: "Unauthorized" }, { status: 401 }));
  }

  if (!["superadmin", "company_admin"].includes(actor.role)) {
    return applySecurityHeaders(NextResponse.json({ error: "Forbidden" }, { status: 403 }));
  }

  let body: CreateUserPayload;
  try {
    body = (await req.json()) as CreateUserPayload;
  } catch {
    return applySecurityHeaders(NextResponse.json({ error: "Invalid JSON" }, { status: 400 }));
  }

  const { displayName, email, password, role, orgId, warehouseId, warehouseIds } = body;

  if (!displayName?.trim())
    return applySecurityHeaders(NextResponse.json({ error: "displayName is required" }, { status: 400 }));
  if (!email?.trim())
    return applySecurityHeaders(NextResponse.json({ error: "email is required" }, { status: 400 }));
  if (password !== undefined && password.length > 0 && password.length < 8)
    return applySecurityHeaders(NextResponse.json({ error: "password must be at least 8 characters" }, { status: 400 }));
  if (!role || !ALLOWED_ROLES.includes(role))
    return applySecurityHeaders(NextResponse.json({ error: `Unknown role: ${role}` }, { status: 400 }));

  // Auto-generate when caller didn't provide one. We always issue a temp
  // password and force the user to change it on first login.
  const wasAutoGenerated = !password;
  const effectivePassword = password && password.length > 0 ? password : generateTempPassword();

  // Superadmin can create users in any org; others are scoped to their own org
  const targetOrgId = actor.role === "superadmin" && orgId ? orgId : actor.org;

  const normalizedWarehouseIds = Array.isArray(warehouseIds)
    ? Array.from(new Set(warehouseIds.filter((id) => typeof id === "string" && id.trim())))
    : [];

  if (role === "regional_manager" && normalizedWarehouseIds.length === 0) {
    return applySecurityHeaders(
      NextResponse.json({ error: "Regional managers must be assigned to at least one warehouse" }, { status: 400 }),
    );
  }

  // Map super_admin → superadmin for DB enum
  const dbRole = role === "super_admin" ? "superadmin" : role;

  // Regional managers have no single primary warehouse
  const effectiveWarehouseId = role === "regional_manager" ? null : (warehouseId || null);

  // Enforce single company_admin per org
  if (dbRole === "company_admin") {
    const [existing] = await db`
      SELECT id FROM users WHERE org_id = ${targetOrgId} AND role = 'company_admin' LIMIT 1
    `;
    if (existing) {
      return applySecurityHeaders(
        NextResponse.json({ error: "This company already has a Company Admin" }, { status: 409 }),
      );
    }
  }

  // Enforce single wh_manager per warehouse
  if (dbRole === "wh_manager" && effectiveWarehouseId) {
    const [existing] = await db`
      SELECT id FROM users
      WHERE  warehouse_id = ${effectiveWarehouseId} AND role = 'wh_manager' AND is_active = true
      LIMIT  1
    `;
    if (existing) {
      return applySecurityHeaders(
        NextResponse.json({ error: "This warehouse already has an active Warehouse Manager" }, { status: 409 }),
      );
    }
  }

  // Email uniqueness within org
  const [dup] = await db`
    SELECT id FROM users WHERE org_id = ${targetOrgId} AND email = ${email.trim().toLowerCase()} LIMIT 1
  `;
  if (dup) {
    return applySecurityHeaders(NextResponse.json({ error: "Email already in use" }, { status: 409 }));
  }

  const uid = uuidv7();
  const hash = await hashPassword(effectivePassword);
  const cleanedEmail = email.trim().toLowerCase();

  await db`
    INSERT INTO users (
      id, org_id, email, password_hash, role, full_name,
      warehouse_id, warehouse_ids, is_active, mfa_required, force_password_reset
    ) VALUES (
      ${uid}, ${targetOrgId}, ${cleanedEmail}, ${hash},
      ${dbRole}, ${displayName.trim()}, ${effectiveWarehouseId},
      ${normalizedWarehouseIds}, true, false, true
    )
  `;

  await recordPasswordHistory(uid, hash);

  // ── Onboarding email (best-effort; failure does not block creation) ───────
  try {
    const [org] = await db`SELECT name FROM orgs WHERE id = ${targetOrgId} LIMIT 1`;
    const companyName = (org?.name as string | undefined) ?? "FleetGuard";
    const { subject, html } = emailUserOnboarding({
      name:         displayName.trim(),
      companyName,
      email:        cleanedEmail,
      tempPassword: effectivePassword,
    });
    void sendMail({ to: cleanedEmail, subject, html });
  } catch (err) {
    console.error("[users/create] onboarding email failed", err);
  }

  await writeAuditEvent({
    orgId: targetOrgId,
    actorId: actor.sub,
    actorRole: actor.role,
    action: "user.created",
    resourceType: "user",
    resourceId: uid,
    ip: req.headers.get("x-forwarded-for")?.split(",")[0]?.trim(),
    payload: {
      email: cleanedEmail,
      role:  dbRole,
      passwordAutoGenerated: wasAutoGenerated,
    },
  });

  return applySecurityHeaders(NextResponse.json({ ok: true, uid }));
}
