import { IncidentCategory, SeverityLevel } from '@/types';

export const INCIDENT_CATEGORIES: Record<IncidentCategory, string> = {
  flood: 'Flood',
  heavy_rain: 'Heavy Rain',
  waterlogging: 'Waterlogging',
  protest: 'Protest',
  morcha: 'Morcha',
  bandh: 'Bandh',
  farmer_protest: 'Farmer Protest',
  strike: 'Strike',
  riot: 'Riot',
  curfew: 'Curfew',
  fire: 'Fire',
  accident: 'Accident',
  traffic_jam: 'Traffic Jam',
  road_block: 'Road Block',
  highway_blockage: 'Highway Blockage',
  train_delay: 'Train Delay',
  metro_disruption: 'Metro Disruption',
  internet_shutdown: 'Internet Shutdown',
  landslide: 'Landslide',
  cyclone: 'Cyclone',
  public_emergency: 'Public Emergency',
  rally: 'Rally',
  vip_movement: 'VIP Movement',
  public_gathering: 'Public Gathering',
  religious_procession: 'Religious Procession',
  festival_crowd: 'Festival Crowd',
  election_rally: 'Election Rally',
  transport_disruption: 'Transport Disruption',
  other: 'Other',
};

export const SEVERITY_COLORS: Record<SeverityLevel, string> = {
  CRITICAL: '#ef4444',
  HIGH: '#f97316',
  MEDIUM: '#eab308',
  LOW: '#22c55e',
  UNKNOWN: '#6b7280',
};

export const CATEGORY_KEYWORDS: Record<IncidentCategory, string[]> = {
  flood: ['flood', 'flooding', 'बाढ़', 'पूर', 'पूर आला'],
  heavy_rain: ['heavy rain', 'torrential rain', 'भारी बारिश', 'भारी पाऊस'],
  waterlogging: ['waterlogging', 'waterlogged', 'जलभराव', 'पाणी साचले'],
  protest: ['protest', 'agitation', 'dharna', 'आंदोलन', 'विरोध'],
  morcha: [
    'morcha',
    'march',
    'protest march',
    'मोर्चा',
    'जुलूस',
  ],
  bandh: ['bandh', 'shutdown', 'बंद', 'हड़ताल'],
  farmer_protest: ['farmer protest', 'kisan', 'किसान आंदोलन'],
  strike: ['strike', 'hartal', 'हड़ताल', 'बंद'],
  riot: ['riot', 'violence', 'दंगा', 'हिंसा'],
  curfew: ['curfew', 'कर्फ्यू', 'संचारबंदी'],
  fire: ['fire', 'blaze', 'आग', 'अग्निकांड'],
  accident: ['accident', 'crash', 'collision', 'दुर्घटना'],
  traffic_jam: ['traffic jam', 'traffic congestion', 'जाम', 'ट्रैफिक'],
  road_block: ['road block', 'road closed', 'रास्ता बंद'],
  highway_blockage: ['highway block', 'NH blocked', 'राजमार्ग बंद'],
  train_delay: ['train delay', 'train cancelled', 'ट्रेन देरी'],
  metro_disruption: ['metro disruption', 'metro closed', 'मेट्रो बंद'],
  internet_shutdown: ['internet shutdown', 'internet blocked', 'इंटरनेट बंद'],
  landslide: ['landslide', 'भूस्खलन', 'दरड कोसळणे'],
  cyclone: ['cyclone', 'storm', 'चक्रवात', 'तूफान'],
  public_emergency: ['emergency', 'disaster', 'आपातकाल', 'आपत्ती'],
  rally: [
    'rally',
    'political rally',
    'public meeting',
    'सभा',
    'रैली',
  ],
  vip_movement: [
    'VIP movement',
    'VVIP movement',
    'PM visit',
    'CM visit',
    'minister visit',
    'security deployment',
    'convoy',
    'traffic restriction',
  ],
  public_gathering: [
    'public gathering',
    'crowd',
    'mass gathering',
    'large gathering',
    'भीड़',
  ],
  religious_procession: ['procession', 'yatra', 'shobhayatra', 'यात्रा', 'जुलूस'],
  festival_crowd: ['festival', 'celebration', 'त्योहार', 'उत्सव'],
  election_rally: ['election rally', 'campaign', 'चुनाव', 'प्रचार'],
  transport_disruption: ['bus strike', 'transport disruption', 'परिवहन बंद'],
  other: [],
};

export const PAST_QUERY_TEMPLATES = [
  '{location} traffic update',
  '{location} traffic jam',
  '{location} road blocked',
  '{location} road closure',
  '{location} diversion',
  '{location} accident today',
  '{location} highway blocked',
  '{location} protest today',
  '{location} bandh today',
  '{location} heavy rain today',
  '{location} waterlogging today',
  '{location} train delay today',
  '{location} metro disruption',
  '{location} public gathering',
  '{location} festival crowd',
  '{location} live traffic',
  '{location} travel advisory',
];

export const FUTURE_QUERY_TEMPLATES = [
  '{location} traffic advisory next 7 days',
  '{location} road closure next 7 days',
  '{location} planned diversion',
  '{location} rally this week',
  '{location} morcha this week',
  '{location} protest this week',
  '{location} bandh this week',
  '{location} CM visit',
  '{location} PM visit',
  '{location} minister visit',
  '{location} VIP movement',
  '{location} political rally',
  '{location} election campaign',
  '{location} public gathering',
  '{location} procession',
  '{location} yatra',
  '{location} shobhayatra',
  '{location} festival traffic',
  '{location} event this weekend',
  '{location} heavy traffic expected',
  '{location} railway maintenance',
  '{location} metro shutdown',
  '{location} travel advisory',
  '{location} security deployment',
  '{location} route diversion',
];

export const RSS_SOURCES = [
  'https://news.google.com/rss/search?q={query}&hl=en-IN&gl=IN&ceid=IN:en',
  'https://timesofindia.indiatimes.com/rssfeeds/913168846.cms',
  'https://feeds.feedburner.com/ndtvnews-india-news',
  'https://www.thehindu.com/feeder/default.rss',
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Puducherry', 'Chandigarh',
];

export const MAX_ARTICLES_TO_SCRAPE = 20;
export const REQUEST_TIMEOUT_MS = 15000;
export const SCRAPE_TIMEOUT_MS = 20000;
export const MAX_PARALLEL_SCRAPES = 5;

export const EVENT_PRIORITY: Record<string, number> = {
  bandh: 10,
  morcha: 9,
  protest: 9,
  vip_movement: 8,
  rally: 8,
  election_rally: 8,
  road_block: 8,
  highway_blockage: 9,
  traffic_jam: 7,
  religious_procession: 7,
  public_gathering: 6,
  festival_crowd: 6,
  train_delay: 5,
  metro_disruption: 5,
  heavy_rain: 5,
};