export const FUTURE_EVENT_INTENTS = [
  'traffic restrictions',
  'traffic advisory',
  'road closure',
  'route diversion',
  'metro disruption',
  'railway maintenance',
  'VIP movement',
  'CM visit',
  'PM visit',
  'protest',
  'morcha',
  'rally',
  'public gathering',
  'religious procession',
  'festival crowd',
  'strike',
  'bandh',
  'election rally',
];