"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles, RefreshCw, AlertCircle } from "lucide-react";
import { api, ApiError } from "../../_services/v2/api";
import { Chip } from "./InsightsShell";

export interface InsightsSummaryPayload {
  scope: "warehouse" | "org";
  warehouseName?: string;
  warehouseCount?: number;
  windowDays: number;
  metrics: {
    totalGateEvents: number;
    uniqueDrivers: number;
    flaggedDrivers: number;
    invalidDl: number;
    expiredDl: number;
    courtCases: number;
    activeCriminal: number;
    openAlerts: number;
    criticalAlerts: number;
    spCount?: number;
    topRiskSp?: { name: string; total: number };
  };
}

interface SummaryResponse {
  headline: string;
  narrative: string;
  insights: string[];
  generatedAt: string;
  source: "openai" | "fallback";
}

export function AISummaryCard({
  payload,
  ready,
  dark = false,
}: {
  payload: InsightsSummaryPayload | null;
  ready: boolean;
  dark?: boolean;
}) {
  const [data, setData]       = useState<SummaryResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr]         = useState<string | null>(null);
  const lastSig               = useRef<string>("");

  const refresh = async (force = false) => {
    if (!payload) return;
    const sig = JSON.stringify(payload);
    if (!force && sig === lastSig.current && data) return;
    lastSig.current = sig;
    setLoading(true);
    setErr(null);
    try {
      const j = await api.post<SummaryResponse>("/api/v2/insights/summary", { payload, force });
      setData(j);
    } catch (e) {
      const msg = e instanceof ApiError ? e.message : e instanceof Error ? e.message : "Failed to generate summary";
      setErr(msg);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (ready && payload) refresh(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ready, payload && JSON.stringify(payload)]);

  /* ── Dark (InsightsShell) variant ─────────────────────────────────────── */
  if (dark) {
    return (
      <div className="relative">
        {/* Header */}
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <Chip tone="brand" dot>
            <Sparkles className="mr-1 h-3 w-3" />
            AI Executive Summary
          </Chip>
          {data?.source === "fallback" && (
            <Chip tone="default">Local rules · OpenAI key not configured</Chip>
          )}
          {data?.source === "openai" && (
            <Chip tone="emerald">Generated by GPT</Chip>
          )}
          <button
            type="button"
            onClick={() => refresh(true)}
            disabled={loading || !ready}
            className="ml-auto inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] font-medium text-slate-400 transition hover:border-white/20 hover:text-white disabled:opacity-40"
          >
            <RefreshCw className={loading ? "h-3 w-3 animate-spin" : "h-3 w-3"} />
            {loading ? "Generating…" : "Regenerate"}
          </button>
        </div>

        {!ready && <DarkSkeleton />}

        {ready && err && (
          <div className="flex items-start gap-3 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
            <div>
              <div className="font-semibold">Could not generate summary</div>
              <div className="mt-0.5 text-red-400/80">{err}</div>
            </div>
          </div>
        )}

        {ready && !err && data && (
          <>
            <h3 className="bg-gradient-to-r from-[#93c5fd] via-[#3d94ff] to-[#6ee7b7] bg-clip-text text-2xl font-bold leading-tight tracking-tight text-transparent md:text-3xl">
              {data.headline}
            </h3>
            <p className="mt-3 text-[15px] leading-relaxed text-slate-200 md:text-base">
              {data.narrative}
            </p>
            {data.insights.length > 0 && (
              <ul className="mt-5 grid gap-3 md:grid-cols-3">
                {data.insights.slice(0, 3).map((insight, i) => (
                  <li
                    key={i}
                    className="rounded-xl border border-white/8 bg-white/[.03] p-3 text-[13px] leading-snug text-slate-300"
                  >
                    <span className="num mr-1.5 text-[11px] font-bold text-brand-400">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    {insight}
                  </li>
                ))}
              </ul>
            )}
            <div className="mt-4 text-[10.5px] uppercase tracking-wider text-slate-500">
              Generated {new Date(data.generatedAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}
            </div>
          </>
        )}

        {ready && !err && !data && loading && <DarkSkeleton />}
      </div>
    );
  }

  /* ── Light (portal) variant ───────────────────────────────────────────── */
  return (
    <div className="rounded-xl border border-blue-100 bg-gradient-to-br from-blue-50 via-white to-white p-5 shadow-sm md:p-6">
      {/* Header row */}
      <div className="mb-4 flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-1.5 rounded-full border border-blue-200 bg-blue-100 px-2.5 py-1 text-[11px] font-semibold text-blue-700">
          <Sparkles className="h-3 w-3" />
          AI Executive Summary
        </span>
        <button
          type="button"
          onClick={() => refresh(true)}
          disabled={loading || !ready}
          className="ml-auto inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-[11px] font-medium text-slate-500 transition hover:border-slate-300 hover:text-slate-800 disabled:opacity-40"
        >
          <RefreshCw className={loading ? "h-3 w-3 animate-spin" : "h-3 w-3"} />
          {loading ? "Generating…" : "Regenerate"}
        </button>
      </div>

      {!ready && <LightSkeleton />}

      {ready && err && (
        <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <div>
            <div className="font-semibold">Could not generate summary</div>
            <div className="mt-0.5 text-red-600/80">{err}</div>
          </div>
        </div>
      )}

      {ready && !err && data && (
        <>
          <h3 className="text-xl font-bold leading-tight tracking-tight text-[#0f2347] md:text-2xl">
            {data.headline}
          </h3>
          <p className="mt-2.5 text-[14px] leading-relaxed text-slate-600 md:text-[15px]">
            {data.narrative}
          </p>
          {data.insights.length > 0 && (
            <ul className="mt-4 grid gap-3 md:grid-cols-3">
              {data.insights.slice(0, 3).map((insight, i) => (
                <li
                  key={i}
                  className="rounded-xl border border-blue-100 bg-white p-3.5 text-[13px] leading-snug text-slate-600 shadow-sm"
                >
                  <span className="num mr-1.5 text-[11px] font-bold text-blue-600">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  {insight}
                </li>
              ))}
            </ul>
          )}
          <div className="mt-3.5 text-[10.5px] uppercase tracking-wider text-slate-400">
            Generated {new Date(data.generatedAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}
          </div>
        </>
      )}

      {ready && !err && !data && loading && <LightSkeleton />}
    </div>
  );
}

function DarkSkeleton() {
  return (
    <div className="animate-pulse space-y-3">
      <div className="h-7 w-3/4 rounded-lg bg-white/10" />
      <div className="h-4 w-full rounded bg-white/5" />
      <div className="h-4 w-11/12 rounded bg-white/5" />
      <div className="h-4 w-9/12 rounded bg-white/5" />
      <div className="mt-4 grid gap-3 md:grid-cols-3">
        {[0, 1, 2].map((i) => (
          <div key={i} className="h-16 rounded-xl border border-white/8 bg-white/[.03]" />
        ))}
      </div>
    </div>
  );
}

function LightSkeleton() {
  return (
    <div className="animate-pulse space-y-3">
      <div className="h-6 w-2/3 rounded-md bg-slate-200" />
      <div className="h-3.5 w-full rounded bg-slate-100" />
      <div className="h-3.5 w-11/12 rounded bg-slate-100" />
      <div className="h-3.5 w-9/12 rounded bg-slate-100" />
      <div className="mt-4 grid gap-3 md:grid-cols-3">
        {[0, 1, 2].map((i) => (
          <div key={i} className="h-16 rounded-xl border border-slate-100 bg-slate-50" />
        ))}
      </div>
    </div>
  );
}
