import { z } from 'zod';

export const IncidentSchema = z.object({
    title: z.string().nullable().optional(),
    severity: z.enum([
        'CRITICAL',
        'HIGH',
        'MEDIUM',
        'LOW',
        'UNKNOWN',
    ]).nullable().optional(),

    status: z.enum([
        'ACTIVE',
        'PAST',
        'UPCOMING',
    ]).nullable().optional(),

    category: z.enum([
        'flood',
        'heavy_rain',
        'waterlogging',
        'protest',
        'morcha',
        'bandh',
        'farmer_protest',
        'strike',
        'riot',
        'curfew',
        'fire',
        'accident',
        'traffic_jam',
        'road_block',
        'highway_blockage',
        'train_delay',
        'metro_disruption',
        'internet_shutdown',
        'landslide',
        'cyclone',
        'public_emergency',
        'rally',
        'vip_movement',
        'public_gathering',
        'religious_procession',
        'festival_crowd',
        'election_rally',
        'transport_disruption',
        'other',
    ]).nullable().optional(),
    eventDate: z.string().nullable().optional(),
    endDate: z.string().nullable().optional(),
    trafficImpact: z.string().nullable().optional(),
    travelAdvisory: z.string().nullable().optional(),
    affectedAreas: z.array(z.string()).default([]),
    affectedRoutes: z.array(z.string()).default([]),
    confidence: z.number().min(0).max(1).default(0.5),
});