import type { Disruption, Advisory, RegionRisk, ControlTowerStats } from "./types";

export const MOCK_DISRUPTIONS: Disruption[] = [
  {
    id: "d1",
    title: "Farmers' Protest Blocking NH44 — Panipat to Ambala",
    category: "political",
    risk: "critical",
    region: "Haryana North",
    state: "Haryana",
    highway: "NH44",
    lat: 29.39,
    lng: 76.97,
    summary: "Large-scale farmers' rally blocking NH44 between Panipat and Ambala. Traffic halted in both directions. Police deployed.",
    detail: "An estimated 15,000 farmers have gathered on NH44 at the Shambhu border point demanding MSP legislation. The blockade has been active since 06:00 IST. Delhi Police and Haryana Police are present but have not attempted to disperse the crowd. NH44 serves as the primary Delhi-Chandigarh-Jammu freight corridor.",
    source: "Punjab Kesari, ANI, Google Traffic",
    impact: "Complete stoppage. No movement possible on NH44 between Panipat and Ambala. Diversion via NH709 adding 4–5 hours.",
    eta_impact_hours: 6,
    started_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 18 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Delhi–Chandigarh", "Delhi–Amritsar", "Delhi–Jammu"],
  },
  {
    id: "d2",
    title: "Cyclone Remal Landfall Alert — Odisha Coastal NH16",
    category: "natural_disaster",
    risk: "critical",
    region: "Odisha Coast",
    state: "Odisha",
    highway: "NH16",
    lat: 20.46,
    lng: 85.88,
    summary: "Cyclone Remal making landfall near Puri. NH16 (Kolkata–Chennai corridor) completely suspended. Storm surge warning in effect.",
    detail: "IMD has issued a red alert for Puri, Khorda, and Ganjam districts. Winds up to 120 km/h expected. NH16 will remain closed until wind speed drops below 50 km/h. NDRF teams deployed. All heavy vehicles banned from coastal highways.",
    source: "IMD, Odisha State Disaster Management",
    impact: "NH16 closed. All Chennai-bound and Kolkata-bound freight must reroute via NH37 and NH149 (adding 8–10 hours).",
    eta_impact_hours: 14,
    started_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 36 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Kolkata–Bhubaneswar", "Bhubaneswar–Chennai", "Vizag–Kolkata"],
  },
  {
    id: "d3",
    title: "VVIP PM Convoy — NH48 Bengaluru to Mysuru",
    category: "vvip",
    risk: "high",
    region: "Karnataka South",
    state: "Karnataka",
    highway: "NH275",
    lat: 12.52,
    lng: 76.89,
    summary: "Prime Minister convoy movement on NH275 Bengaluru–Mysuru. Highway closed from 14:00–18:00 IST today.",
    detail: "SPG has notified Bengaluru Traffic Police of PM convoy movement from Kempegowda International Airport to Mysuru for an official event. NH275 will be subject to rolling closures with zero vehicle movement during convoy passage. All freight advised to hold or use NICE corridor as alternative.",
    source: "Karnataka Traffic Police Advisory, SPG Notification",
    impact: "4-hour window closure on NH275. Heavy vehicles must use NH48/NICE road (adding 1.5 hours).",
    eta_impact_hours: 2,
    started_at: new Date(Date.now() + 1 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 5 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Bengaluru–Mysuru", "Bengaluru–Coorg"],
  },
  {
    id: "d4",
    title: "Flash Floods — NH48 Pune Ghat Section",
    category: "weather",
    risk: "high",
    region: "Pune Ghats",
    state: "Maharashtra",
    highway: "NH48",
    lat: 18.52,
    lng: 73.85,
    summary: "Heavy rainfall causing flash floods on NH48 Pune–Mumbai ghat section. Landslide debris on road near Khopoli.",
    detail: "IMD Yellow Alert for Pune and Raigad districts. Multiple waterlogging points reported between Khopoli and Khalapur. A landslide has partially blocked the highway near Khopoli Toll Plaza. MSRDC teams deployed for debris clearance. One lane operational.",
    source: "IMD Pune, MSRDC, Google Traffic",
    impact: "30–45 minute delay minimum. Night dispatch advised against. NH4 (Old Mumbai-Pune Highway) as alternative via Dehu Road.",
    eta_impact_hours: 1.5,
    started_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 6 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Mumbai–Pune", "Mumbai–Solapur"],
  },
  {
    id: "d5",
    title: "BJP Maharashtra Bandh — Mumbai MMR",
    category: "political",
    risk: "high",
    region: "Mumbai Metropolitan",
    state: "Maharashtra",
    highway: "Multiple",
    lat: 19.07,
    lng: 72.87,
    summary: "Opposition-called bandh across Mumbai Metropolitan Region. Petrol pumps, shops closed. Sporadic road blockades.",
    detail: "The bandh call is active 06:00–18:00 IST. Reports of stone-pelting at isolated locations in Dharavi and Kurla areas. Mumbai-Nashik Expressway and Eastern Express Highway running but with reduced visibility of law and order. Essential services exempt.",
    source: "Mumbai Police Advisory, NDTV, Economic Times",
    impact: "Movement possible but high security risk. Advise delaying Mumbai city deliveries to post-18:00. Cargo insurance may not cover bandh-related damage.",
    eta_impact_hours: 3,
    started_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 13 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Mumbai–Nashik", "Mumbai–Pune", "Mumbai Intra-City"],
  },
  {
    id: "d6",
    title: "Bridge Weight Restriction — NH37 Guwahati",
    category: "infrastructure",
    risk: "medium",
    region: "Assam Central",
    state: "Assam",
    highway: "NH37",
    lat: 26.14,
    lng: 91.74,
    summary: "Saraighat Bridge load restriction imposed. Vehicles over 40 tonnes prohibited pending structural inspection.",
    detail: "NHAI has imposed a 40-tonne gross vehicle weight limit on the Saraighat Bridge following preliminary inspection findings. Heavy mining trucks and tankers carrying full loads must use the Lower Assam route via NH27. Restriction in force for 30 days.",
    source: "NHAI Circular #2024-AS-112, Assam PWD",
    impact: "Overloaded vehicles must reroute via NH27 (adding 90 minutes). Split loads or lightening recommended for urgent deliveries.",
    eta_impact_hours: 1.5,
    started_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 30 * 24 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Guwahati–Jorhat", "Guwahati–Dibrugarh"],
  },
  {
    id: "d7",
    title: "Kumbh Mela Religious Procession — Prayagraj NH30",
    category: "religious",
    risk: "medium",
    region: "Prayagraj",
    state: "Uttar Pradesh",
    highway: "NH30",
    lat: 25.43,
    lng: 81.84,
    summary: "Major Amrit Snan (holy bath) procession expected to draw 2–3 million pilgrims. NH30 will face significant congestion.",
    detail: "The Mauni Amavasya Snan is scheduled. City police have imposed heavy vehicle restrictions on NH30 within 50km of Sangam from midnight to 14:00 IST. Container trucks and multi-axle vehicles must use NH19 bypass.",
    source: "Prayagraj Police, UP Transport Department",
    impact: "Heavy vehicle ban on NH30 until 14:00. Use NH19 bypass. Delay Prayagraj deliveries to post-14:00.",
    eta_impact_hours: 2,
    started_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 10 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Varanasi–Prayagraj", "Lucknow–Prayagraj"],
  },
  {
    id: "d8",
    title: "Highway Robbery Hotspot — NH52 Rajasthan Night Zone",
    category: "security",
    risk: "high",
    region: "Rajasthan East",
    state: "Rajasthan",
    highway: "NH52",
    lat: 26.91,
    lng: 75.78,
    summary: "Three cargo theft incidents reported on NH52 between Jaipur and Dausa in the past 7 days. Night travel advisory issued.",
    detail: "Rajasthan Police has issued a cargo security advisory for NH52 between Jaipur and Dausa, specifically the 22:00–05:00 window. Incidents involved diversions by fake policemen and subsequent theft. CCTV blind spots identified at Baswa and Bandikui segments.",
    source: "Rajasthan Police Advisory, Industry CISC",
    impact: "Avoid night dispatch on NH52. Escort recommended for high-value cargo. Travel in convoy if possible.",
    eta_impact_hours: 0,
    started_at: new Date(Date.now() - 7 * 24 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Jaipur–Dausa", "Jaipur–Agra"],
  },
  {
    id: "d9",
    title: "Highway Construction — NH44 Nagpur CSTM Flyover",
    category: "infrastructure",
    risk: "low",
    region: "Nagpur",
    state: "Maharashtra",
    highway: "NH44",
    lat: 21.14,
    lng: 79.08,
    summary: "NHAI flyover construction causing single-lane traffic on NH44 near CSTM junction. Expected 45-minute delays peak hours.",
    detail: "Nagpur CSTM Flyover Phase 2 construction is active. One lane open at all times. Traffic signals deployed. Delays of 30–60 minutes expected during 08:00–10:00 and 17:00–20:00. Night movement (22:00–06:00) runs normally.",
    source: "NHAI Nagpur Division, Maharashtra Traffic",
    impact: "Avoid peak hours at Nagpur CSTM stretch. Night movement recommended for time-critical cargo.",
    eta_impact_hours: 0.75,
    started_at: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 60 * 24 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Delhi–Hyderabad via Nagpur", "Mumbai–Nagpur"],
  },
  {
    id: "d10",
    title: "Dense Fog Advisory — NH24 Delhi–Lucknow",
    category: "weather",
    risk: "medium",
    region: "Western UP",
    state: "Uttar Pradesh",
    highway: "NH24",
    lat: 28.62,
    lng: 77.82,
    summary: "IMD dense fog advisory active for NH24 Ghaziabad–Moradabad section. Visibility below 50m reported between 01:00–09:00.",
    detail: "Dense fog conditions expected to persist for the next 3 days. Pile-up risk is high between Hapur and Moradabad. Multiple accidents recorded. Expressway authority has imposed 60 km/h speed limit. Fog lights mandatory.",
    source: "IMD UP Division, UP Expressways Authority",
    impact: "Night dispatch not recommended. Allow 3-hour buffer for morning dispatches. Ensure vehicle fog lights operational.",
    eta_impact_hours: 2,
    started_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    expected_clear_at: new Date(Date.now() + 60 * 3600000).toISOString(),
    verified: true,
    affectedRoutes: ["Delhi–Lucknow", "Delhi–Gorakhpur"],
  },
];

export const MOCK_ADVISORIES: Advisory[] = [
  {
    id: "a1",
    title: "HOLD all Delhi–Chandigarh dispatches for next 18 hours",
    type: "hold",
    region: "Haryana North",
    highway: "NH44",
    riskLevel: "critical",
    confidence: 97,
    narrative: "NH44 is completely blocked due to farmers' protest at Shambhu border. No alternate route can absorb high-tonnage freight within acceptable time windows. Holding dispatch is the optimal decision. Estimated clearance window opens at 02:00 IST tomorrow.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 18 * 3600000).toISOString(),
    affectedZones: ["Panipat", "Kurukshetra", "Ambala", "Ludhiana"],
    recommendedAction: "Hold all vehicles at origin. Notify consignees of 18–24 hour delay. Check back at 22:00 IST for corridor re-assessment.",
    isUrgent: true,
  },
  {
    id: "a2",
    title: "REROUTE Mumbai–Pune freight via NH4 until 20:00",
    type: "reroute",
    region: "Pune Ghats",
    highway: "NH48",
    riskLevel: "high",
    confidence: 89,
    narrative: "Flash flooding and landslide debris on NH48 ghat section makes it unsafe for heavy vehicles. The Old Mumbai–Pune Highway (NH4) via Dehu Road adds 35 km but is currently clear and safe. Weather expected to improve by 20:00 IST.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 6 * 3600000).toISOString(),
    affectedZones: ["Khopoli", "Khalapur", "Pune Ghat"],
    recommendedAction: "Use NH4 via Dehu Road. Brief drivers on alternate route. Update ETA by +75 minutes.",
    isUrgent: true,
  },
  {
    id: "a3",
    title: "DISPATCH EARLY — Bengaluru–Mysuru cargo before 13:30",
    type: "dispatch_early",
    region: "Karnataka South",
    highway: "NH275",
    riskLevel: "high",
    confidence: 95,
    narrative: "VVIP convoy movement will close NH275 from 14:00–18:00 IST. Vehicles that depart Bengaluru before 13:30 can clear the corridor. Post-18:00 window is also safe. Dead zone is 14:00–18:00 only.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 2 * 3600000).toISOString(),
    affectedZones: ["Bengaluru", "Ramnagara", "Mandya", "Mysuru"],
    recommendedAction: "Dispatch before 13:30 IST. If not possible, hold until 18:30 IST. Do not dispatch 13:30–18:00 window.",
    isUrgent: true,
  },
  {
    id: "a4",
    title: "AVOID NIGHT TRAVEL on NH52 Rajasthan corridor",
    type: "avoid_night",
    region: "Rajasthan East",
    highway: "NH52",
    riskLevel: "high",
    confidence: 92,
    narrative: "Pattern analysis shows 3 cargo theft incidents in 7 days on NH52 between 22:00–05:00. Probability of incident for unescorted high-value cargo is estimated at 18% per night transit. Risk does not apply during daytime hours.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 7 * 24 * 3600000).toISOString(),
    affectedZones: ["Dausa", "Baswa", "Bandikui"],
    recommendedAction: "Schedule NH52 transit for 06:00–20:00 window only. Engage escort for high-value cargo.",
    isUrgent: false,
  },
  {
    id: "a5",
    title: "SPLIT SHIPMENT — Cyclone-affected Odisha corridor",
    type: "split_shipment",
    region: "Odisha Coast",
    highway: "NH16",
    riskLevel: "critical",
    confidence: 88,
    narrative: "Cyclone Remal closure of NH16 is expected to last 36+ hours. If delivery is time-critical, splitting the shipment and routing partial loads via Nagpur–Vijayawada corridor may preserve partial SLA compliance.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 36 * 3600000).toISOString(),
    affectedZones: ["Bhubaneswar", "Puri", "Berhampur"],
    recommendedAction: "Split shipment. Route 50% via NH16 after clearance. Route remaining 50% via NH37–NH149 now. Coordinate with destination warehouse.",
    isUrgent: false,
  },
  {
    id: "a6",
    title: "DELAY dispatch — Delhi–Lucknow until 10:00 IST",
    type: "delay",
    region: "Western UP",
    highway: "NH24",
    riskLevel: "medium",
    confidence: 84,
    narrative: "Dense fog on NH24 (Yamuna Expressway + Lucknow Expressway) creates dangerous driving conditions until approximately 09:30 IST. Pile-up risk is elevated. Delaying dispatch to 10:00 IST ensures full daylight and fog-clear conditions.",
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 5 * 3600000).toISOString(),
    affectedZones: ["Ghaziabad", "Hapur", "Moradabad"],
    recommendedAction: "Hold Delhi–Lucknow vehicles until 10:00 IST. ETA adjustment: +3 hours from original schedule.",
    isUrgent: false,
  },
];

export const MOCK_REGION_RISKS: RegionRisk[] = [
  { region: "Haryana North",        state: "Haryana",       riskLevel: "critical", activeDisruptions: 2, keyIssue: "Farmers' protest NH44" },
  { region: "Odisha Coast",          state: "Odisha",        riskLevel: "critical", activeDisruptions: 1, keyIssue: "Cyclone Remal" },
  { region: "Mumbai Metropolitan",   state: "Maharashtra",   riskLevel: "high",     activeDisruptions: 2, keyIssue: "Bandh + Ghat floods" },
  { region: "Karnataka South",       state: "Karnataka",     riskLevel: "high",     activeDisruptions: 1, keyIssue: "VVIP movement NH275" },
  { region: "Rajasthan East",        state: "Rajasthan",     riskLevel: "high",     activeDisruptions: 1, keyIssue: "Cargo theft hotspot" },
  { region: "Prayagraj",             state: "Uttar Pradesh", riskLevel: "medium",   activeDisruptions: 1, keyIssue: "Kumbh procession NH30" },
  { region: "Western UP",            state: "Uttar Pradesh", riskLevel: "medium",   activeDisruptions: 1, keyIssue: "Dense fog NH24" },
  { region: "Assam Central",         state: "Assam",         riskLevel: "medium",   activeDisruptions: 1, keyIssue: "Bridge weight limit" },
  { region: "Nagpur",                state: "Maharashtra",   riskLevel: "low",      activeDisruptions: 1, keyIssue: "Highway construction" },
  { region: "Tamil Nadu Central",    state: "Tamil Nadu",    riskLevel: "safe",     activeDisruptions: 0, keyIssue: "No active disruptions" },
  { region: "Gujarat",               state: "Gujarat",       riskLevel: "safe",     activeDisruptions: 0, keyIssue: "No active disruptions" },
  { region: "Telangana",             state: "Telangana",     riskLevel: "low",      activeDisruptions: 0, keyIssue: "Minor construction" },
];

export const MOCK_STATS: ControlTowerStats = {
  totalDisruptions: 10,
  criticalAlerts: 2,
  highRiskCorridors: 4,
  safeCorriders: 6,
  pendingAdvisories: 6,
  regionsAffected: 8,
};

export const VEHICLE_TYPES = [
  "Multi-Axle Truck (MAV)",
  "Semi-Trailer / Articulated",
  "Container Truck (20ft)",
  "Container Truck (40ft)",
  "Mini Truck / LCV",
  "Tanker (Liquid)",
  "Tanker (Gas/CNG)",
  "Flatbed / Lowbed",
  "Reefer / Cold Chain",
  "Tipper / Dumper",
];

export const CARGO_TYPES = [
  "FMCG / General Merchandise",
  "Petroleum / Fuel",
  "Chemicals / Hazmat",
  "Pharmaceuticals / Cold Chain",
  "Automotive Parts",
  "Steel / Heavy Metal",
  "Cement / Building Material",
  "Agricultural Produce",
  "Electronics / High Value",
  "E-commerce / Parcels",
  "Mining / Coal",
  "Textiles / Garments",
];

export const MAJOR_CITIES = [
  "Mumbai, Maharashtra",
  "Delhi, NCT",
  "Bengaluru, Karnataka",
  "Chennai, Tamil Nadu",
  "Hyderabad, Telangana",
  "Pune, Maharashtra",
  "Ahmedabad, Gujarat",
  "Kolkata, West Bengal",
  "Surat, Gujarat",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Coimbatore, Tamil Nadu",
  "Kochi, Kerala",
  "Chandigarh, Punjab",
  "Guwahati, Assam",
  "Bhopal, Madhya Pradesh",
  "Patna, Bihar",
  "Bhubaneswar, Odisha",
  "Visakhapatnam, Andhra Pradesh",
  "Raipur, Chhattisgarh",
  "Ludhiana, Punjab",
  "Varanasi, Uttar Pradesh",
];
