import type {
  Advisory,
  Alert,
  CalendarEvent,
  ComplianceBucket,
  Contractor,
  DispatchPlan,
  Disruption,
  Driver,
  GateEvent,
  Incident,
  MonitoredCorridor,
  RegionRisk,
  Trip,
  Vehicle,
  VisitorEntry,
  Warehouse,
} from "./types";

/**
 * Deterministic fixture data for the FleetGuard POC.
 * All timestamps are computed relative to "now" at import time,
 * so the UI always looks fresh. This is intentionally synchronous
 * so it can be consumed from both server and client components.
 */

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60_000);
const hoursAgo = (h: number) => minutesAgo(h * 60);
const daysFromNow = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60_000);

// ── Warehouses ──────────────────────────────────────────────────
// x/y coords are normalised 0..100 against the stylised India SVG
// used on the /cso/live-map screen.
export interface WarehouseGeo extends Warehouse {
  x: number;
  y: number;
  manager: string;
}

export const warehouses: WarehouseGeo[] = [
  {
    id: "wh_mum_01",
    name: "Bhiwandi Hub",
    city: "Bhiwandi",
    state: "Maharashtra",
    region: "West",
    activeTrips: 14,
    openAlerts: 3,
    status: "green",
    x: 26,
    y: 58,
    manager: "Ankit Bhatia",
  },
  {
    id: "wh_pun_01",
    name: "Chakan Logistik",
    city: "Chakan",
    state: "Maharashtra",
    region: "West",
    activeTrips: 10,
    openAlerts: 1,
    status: "green",
    x: 30,
    y: 62,
    manager: "Sneha Pawar",
  },
  {
    id: "wh_ahm_01",
    name: "Sanand DC",
    city: "Sanand",
    state: "Gujarat",
    region: "West",
    activeTrips: 8,
    openAlerts: 2,
    status: "amber",
    x: 22,
    y: 46,
    manager: "Ramesh Gupta",
  },
  {
    id: "wh_del_01",
    name: "Gurugram DC",
    city: "Gurugram",
    state: "Haryana",
    region: "North",
    activeTrips: 11,
    openAlerts: 5,
    status: "amber",
    x: 40,
    y: 28,
    manager: "Priya Nair",
  },
  {
    id: "wh_jai_01",
    name: "Bhiwadi FC",
    city: "Bhiwadi",
    state: "Rajasthan",
    region: "North",
    activeTrips: 5,
    openAlerts: 0,
    status: "green",
    x: 34,
    y: 32,
    manager: "Anand Mehra",
  },
  {
    id: "wh_lko_01",
    name: "Lucknow Hub",
    city: "Lucknow",
    state: "Uttar Pradesh",
    region: "North",
    activeTrips: 6,
    openAlerts: 1,
    status: "green",
    x: 52,
    y: 38,
    manager: "Imran Qureshi",
  },
  {
    id: "wh_blr_01",
    name: "Hoskote FC",
    city: "Hoskote",
    state: "Karnataka",
    region: "South",
    activeTrips: 9,
    openAlerts: 1,
    status: "green",
    x: 42,
    y: 76,
    manager: "Karthik S",
  },
  {
    id: "wh_hyd_01",
    name: "Medchal DC",
    city: "Medchal",
    state: "Telangana",
    region: "South",
    activeTrips: 7,
    openAlerts: 2,
    status: "amber",
    x: 44,
    y: 66,
    manager: "Lakshmi Rao",
  },
  {
    id: "wh_chn_01",
    name: "Sriperumbudur",
    city: "Chennai",
    state: "Tamil Nadu",
    region: "South",
    activeTrips: 12,
    openAlerts: 0,
    status: "green",
    x: 50,
    y: 80,
    manager: "Balaji K",
  },
  {
    id: "wh_coi_01",
    name: "Coimbatore FC",
    city: "Coimbatore",
    state: "Tamil Nadu",
    region: "South",
    activeTrips: 4,
    openAlerts: 0,
    status: "green",
    x: 44,
    y: 84,
    manager: "Senthil Kumar",
  },
  {
    id: "wh_kol_01",
    name: "Dankuni Hub",
    city: "Dankuni",
    state: "West Bengal",
    region: "East",
    activeTrips: 6,
    openAlerts: 4,
    status: "red",
    x: 68,
    y: 48,
    manager: "Bikash Das",
  },
  {
    id: "wh_bbs_01",
    name: "Bhubaneswar DC",
    city: "Bhubaneswar",
    state: "Odisha",
    region: "East",
    activeTrips: 5,
    openAlerts: 1,
    status: "amber",
    x: 62,
    y: 56,
    manager: "Rashmi Behera",
  },
  {
    id: "wh_guw_01",
    name: "Guwahati Hub",
    city: "Guwahati",
    state: "Assam",
    region: "East",
    activeTrips: 3,
    openAlerts: 0,
    status: "green",
    x: 78,
    y: 40,
    manager: "Dibakar Barua",
  },
  {
    id: "wh_bhp_01",
    name: "Bhopal DC",
    city: "Bhopal",
    state: "MP",
    region: "Central",
    activeTrips: 6,
    openAlerts: 1,
    status: "green",
    x: 40,
    y: 48,
    manager: "Suresh Jain",
  },
  {
    id: "wh_ngp_01",
    name: "Nagpur FC",
    city: "Nagpur",
    state: "Maharashtra",
    region: "Central",
    activeTrips: 5,
    openAlerts: 0,
    status: "green",
    x: 44,
    y: 54,
    manager: "Vivek Deshmukh",
  },
];

export const DEFAULT_WAREHOUSE = warehouses[0];

// ── Contractors ─────────────────────────────────────────────────
export const contractors: Contractor[] = [
  {
    id: "ct_01",
    name: "Samarth Logistics",
    contactName: "Rakesh Kulkarni",
    contactMobile: "+91 98201 11201",
    contractEnd: daysFromNow(180),
    activeDrivers: 18,
    activeVehicles: 22,
    isComplete: true,
  },
  {
    id: "ct_02",
    name: "Adarsh Roadways",
    contactName: "Priya Shah",
    contactMobile: "+91 99873 41211",
    contractEnd: daysFromNow(22),
    activeDrivers: 9,
    activeVehicles: 11,
    isComplete: true,
  },
  {
    id: "ct_03",
    name: "BlueArrow Transport",
    contactName: "Imran Khan",
    contactMobile: "+91 98765 41200",
    contractEnd: daysFromNow(410),
    activeDrivers: 24,
    activeVehicles: 30,
    isComplete: true,
  },
  {
    id: "ct_04",
    name: "Hi-Tech Carriers",
    contactName: "—",
    contactMobile: "+91 90234 55167",
    contractEnd: null,
    activeDrivers: 2,
    activeVehicles: 2,
    isComplete: false,
  },
  {
    id: "ct_05",
    name: "Laxmi Freight",
    contactName: "Sunita Joshi",
    contactMobile: "+91 96502 12123",
    contractEnd: daysFromNow(55),
    activeDrivers: 14,
    activeVehicles: 17,
    isComplete: true,
  },
  {
    id: "ct_06",
    name: "Sree Ganesh Cargo",
    contactName: "Manjunath Rao",
    contactMobile: "+91 95123 77091",
    contractEnd: daysFromNow(270),
    activeDrivers: 11,
    activeVehicles: 13,
    isComplete: true,
  },
  {
    id: "ct_07",
    name: "FastLane 3PL",
    contactName: "—",
    contactMobile: "+91 97340 22118",
    contractEnd: null,
    activeDrivers: 4,
    activeVehicles: 4,
    isComplete: false,
  },
  {
    id: "ct_08",
    name: "Orbit Movers",
    contactName: "Ayesha Fernandes",
    contactMobile: "+91 99204 18200",
    contractEnd: daysFromNow(-7),
    activeDrivers: 6,
    activeVehicles: 8,
    isComplete: true,
  },
];

// ── Drivers ─────────────────────────────────────────────────────
export const drivers: Driver[] = [
  {
    id: "drv_01",
    fullName: "Rajesh Kumar",
    mobile: "+91 98111 20034",
    dlNumber: "MH03 20180012345",
    dlExpiry: daysFromNow(540),
    dlStatus: "clear",
    bgStatus: "clear",
    facePhotoUrl: null,
    registeredAt: hoursAgo(3400),
  },
  {
    id: "drv_02",
    fullName: "Suresh Yadav",
    mobile: "+91 98765 00201",
    dlNumber: "DL09 20170034982",
    dlExpiry: daysFromNow(42),
    dlStatus: "expiring",
    bgStatus: "clear",
    facePhotoUrl: null,
    registeredAt: hoursAgo(8120),
  },
  {
    id: "drv_03",
    fullName: "Mohd. Faizal",
    mobile: "+91 90123 66712",
    dlNumber: "KA01 20190066421",
    dlExpiry: daysFromNow(18),
    dlStatus: "blocked",
    bgStatus: "flagged",
    facePhotoUrl: null,
    registeredAt: hoursAgo(11200),
  },
  {
    id: "drv_04",
    fullName: "Vinod Patil",
    mobile: "+91 98220 11210",
    dlNumber: "MH12 20200087211",
    dlExpiry: daysFromNow(720),
    dlStatus: "clear",
    bgStatus: "clear",
    facePhotoUrl: null,
    registeredAt: hoursAgo(1200),
  },
  {
    id: "drv_05",
    fullName: "Harpreet Singh",
    mobile: "+91 98988 42140",
    dlNumber: "PB08 20180012990",
    dlExpiry: daysFromNow(310),
    dlStatus: "clear",
    bgStatus: "pending",
    facePhotoUrl: null,
    registeredAt: hoursAgo(4410),
  },
  {
    id: "drv_06",
    fullName: "Karthik Subramani",
    mobile: "+91 90040 33311",
    dlNumber: "TN22 20190034410",
    dlExpiry: daysFromNow(210),
    dlStatus: "clear",
    bgStatus: "clear",
    facePhotoUrl: null,
    registeredAt: hoursAgo(6610),
  },
  {
    id: "drv_07",
    fullName: "Arjun Deshmukh",
    mobile: "+91 88888 29201",
    dlNumber: "MH14 20190019903",
    dlExpiry: daysFromNow(-12),
    dlStatus: "expired",
    bgStatus: "clear",
    facePhotoUrl: null,
    registeredAt: hoursAgo(9100),
  },
  {
    id: "drv_08",
    fullName: "Bikram Das",
    mobile: "+91 90301 88021",
    dlNumber: "WB02 20170087790",
    dlExpiry: daysFromNow(55),
    dlStatus: "expiring",
    bgStatus: "pending",
    facePhotoUrl: null,
    registeredAt: hoursAgo(2200),
  },
];

// ── Vehicles ────────────────────────────────────────────────────
export const vehicles: Vehicle[] = [
  {
    id: "veh_01",
    registrationNumber: "MH 04 GA 1234",
    vehicleType: "14-T Container",
    ownerType: "contractor",
    contractorId: "ct_01",
    rcExpiry: daysFromNow(540),
    insuranceExpiry: daysFromNow(95),
    fitnessExpiry: daysFromNow(300),
    pucExpiry: daysFromNow(61),
    status: "clear",
  },
  {
    id: "veh_02",
    registrationNumber: "MH 12 LK 9982",
    vehicleType: "9-T Reefer",
    ownerType: "contractor",
    contractorId: "ct_02",
    rcExpiry: daysFromNow(210),
    insuranceExpiry: daysFromNow(19),
    fitnessExpiry: daysFromNow(140),
    pucExpiry: daysFromNow(110),
    status: "expiring",
  },
  {
    id: "veh_03",
    registrationNumber: "HR 55 AB 8821",
    vehicleType: "22-T Trailer",
    ownerType: "contractor",
    contractorId: "ct_03",
    rcExpiry: daysFromNow(-5),
    insuranceExpiry: daysFromNow(410),
    fitnessExpiry: daysFromNow(45),
    pucExpiry: daysFromNow(18),
    status: "blocked",
  },
  {
    id: "veh_04",
    registrationNumber: "KA 05 MN 6601",
    vehicleType: "14-T Container",
    ownerType: "contractor",
    contractorId: "ct_01",
    rcExpiry: daysFromNow(720),
    insuranceExpiry: daysFromNow(340),
    fitnessExpiry: daysFromNow(201),
    pucExpiry: daysFromNow(88),
    status: "clear",
  },
  {
    id: "veh_05",
    registrationNumber: "TN 18 XY 4410",
    vehicleType: "9-T Box Truck",
    ownerType: "contractor",
    contractorId: "ct_05",
    rcExpiry: daysFromNow(140),
    insuranceExpiry: daysFromNow(60),
    fitnessExpiry: daysFromNow(88),
    pucExpiry: daysFromNow(44),
    status: "clear",
  },
  {
    id: "veh_06",
    registrationNumber: "GJ 01 RT 7712",
    vehicleType: "32-T Multi-axle",
    ownerType: "contractor",
    contractorId: "ct_03",
    rcExpiry: daysFromNow(290),
    insuranceExpiry: daysFromNow(210),
    fitnessExpiry: daysFromNow(140),
    pucExpiry: daysFromNow(29),
    status: "expiring",
  },
  {
    id: "veh_07",
    registrationNumber: "MH 14 DK 3301",
    vehicleType: "14-T Container",
    ownerType: "contractor",
    contractorId: "ct_01",
    rcExpiry: daysFromNow(385),
    insuranceExpiry: daysFromNow(165),
    fitnessExpiry: daysFromNow(245),
    pucExpiry: daysFromNow(120),
    status: "clear",
  },
  {
    id: "veh_08",
    registrationNumber: "UP 16 LM 7520",
    vehicleType: "22-T Trailer",
    ownerType: "contractor",
    contractorId: "ct_03",
    rcExpiry: daysFromNow(34),
    insuranceExpiry: daysFromNow(122),
    fitnessExpiry: daysFromNow(62),
    pucExpiry: daysFromNow(15),
    status: "expiring",
  },
  {
    id: "veh_09",
    registrationNumber: "DL 8C AB 4411",
    vehicleType: "9-T Box Truck",
    ownerType: "owned",
    contractorId: null,
    rcExpiry: daysFromNow(610),
    insuranceExpiry: daysFromNow(420),
    fitnessExpiry: daysFromNow(312),
    pucExpiry: daysFromNow(190),
    status: "clear",
  },
  {
    id: "veh_10",
    registrationNumber: "TS 09 XP 2240",
    vehicleType: "14-T Container",
    ownerType: "contractor",
    contractorId: "ct_05",
    rcExpiry: daysFromNow(-18),
    insuranceExpiry: daysFromNow(84),
    fitnessExpiry: daysFromNow(132),
    pucExpiry: daysFromNow(71),
    status: "blocked",
  },
  {
    id: "veh_11",
    registrationNumber: "KL 07 QR 9931",
    vehicleType: "9-T Reefer",
    ownerType: "contractor",
    contractorId: "ct_02",
    rcExpiry: daysFromNow(470),
    insuranceExpiry: daysFromNow(275),
    fitnessExpiry: daysFromNow(55),
    pucExpiry: daysFromNow(42),
    status: "expiring",
  },
  {
    id: "veh_12",
    registrationNumber: "WB 22 EF 6671",
    vehicleType: "32-T Multi-axle",
    ownerType: "contractor",
    contractorId: "ct_03",
    rcExpiry: daysFromNow(220),
    insuranceExpiry: daysFromNow(180),
    fitnessExpiry: daysFromNow(410),
    pucExpiry: daysFromNow(101),
    status: "clear",
  },
];

/** Full visitor log for today — includes entries that have already exited. */
export interface VisitorLogEntry extends VisitorEntry {
  status: "inside" | "exited";
  exitTime: Date | null;
}

export const visitorLog: VisitorLogEntry[] = [
  {
    id: "vl_01",
    visitorType: "visitor",
    fullName: "Deepa Menon",
    hostName: "Ankit Bhatia",
    purpose: "Commercial review",
    passNumber: "V-2041",
    entryTime: hoursAgo(1.75),
    expectedExit: hoursAgo(-0.25),
    vehicleNumber: null,
    status: "inside",
    exitTime: null,
  },
  {
    id: "vl_02",
    visitorType: "contractor",
    fullName: "Sachin Bhosale",
    hostName: "Priya Nair",
    purpose: "Rack maintenance",
    passNumber: "C-1122",
    entryTime: hoursAgo(1.2),
    expectedExit: hoursAgo(-3),
    vehicleNumber: "MH 47 PK 2020",
    status: "inside",
    exitTime: null,
  },
  {
    id: "vl_03",
    visitorType: "visitor",
    fullName: "Rohan Iyer",
    hostName: "Rahul Patil",
    purpose: "Safety audit",
    passNumber: "V-2042",
    entryTime: minutesAgo(12),
    expectedExit: hoursAgo(-4),
    vehicleNumber: null,
    status: "inside",
    exitTime: null,
  },
  {
    id: "vl_04",
    visitorType: "auditor",
    fullName: "CA Nisha Rao",
    hostName: "Manoj Verma",
    purpose: "Quarterly stock audit",
    passNumber: "A-0091",
    entryTime: hoursAgo(3),
    expectedExit: hoursAgo(-1),
    vehicleNumber: null,
    status: "inside",
    exitTime: null,
  },
  {
    id: "vl_05",
    visitorType: "maintenance",
    fullName: "Ravi Shankar",
    hostName: "Manoj Verma",
    purpose: "AC servicing",
    passNumber: "M-0332",
    entryTime: hoursAgo(6.5),
    expectedExit: hoursAgo(3),
    vehicleNumber: "MH 04 AT 9821",
    status: "exited",
    exitTime: hoursAgo(2.8),
  },
  {
    id: "vl_06",
    visitorType: "visitor",
    fullName: "Sneha Kulkarni",
    hostName: "Ankit Bhatia",
    purpose: "Logistics review",
    passNumber: "V-2038",
    entryTime: hoursAgo(7),
    expectedExit: hoursAgo(4),
    vehicleNumber: null,
    status: "exited",
    exitTime: hoursAgo(3.5),
  },
  {
    id: "vl_07",
    visitorType: "contractor",
    fullName: "Irfan Sheikh",
    hostName: "Rahul Patil",
    purpose: "Electrical repair",
    passNumber: "C-1121",
    entryTime: hoursAgo(5),
    expectedExit: hoursAgo(2),
    vehicleNumber: "MH 12 KK 1192",
    status: "exited",
    exitTime: hoursAgo(1.9),
  },
  {
    id: "vl_08",
    visitorType: "auditor",
    fullName: "Alok Srivastav",
    hostName: "Manoj Verma",
    purpose: "Safety inspection",
    passNumber: "A-0090",
    entryTime: hoursAgo(8),
    expectedExit: hoursAgo(5),
    vehicleNumber: null,
    status: "exited",
    exitTime: hoursAgo(4.2),
  },
  {
    id: "vl_09",
    visitorType: "visitor",
    fullName: "Priyanka Gupta",
    hostName: "Priya Nair",
    purpose: "Vendor onboarding",
    passNumber: "V-2039",
    entryTime: hoursAgo(4),
    expectedExit: hoursAgo(1),
    vehicleNumber: null,
    status: "exited",
    exitTime: hoursAgo(1.1),
  },
  {
    id: "vl_10",
    visitorType: "other",
    fullName: "Vijay Subramani",
    hostName: "Rahul Patil",
    purpose: "Fire drill coordinator",
    passNumber: "V-2040",
    entryTime: hoursAgo(3.5),
    expectedExit: hoursAgo(1),
    vehicleNumber: null,
    status: "exited",
    exitTime: hoursAgo(0.8),
  },
];

// ── Trips (with stops) ──────────────────────────────────────────
export const trips: Trip[] = [
  {
    id: "trp_01",
    tripCode: "TRP-20260415-0142",
    vehicleId: "veh_01",
    vehicleReg: "MH 04 GA 1234",
    driverId: "drv_01",
    driverName: "Rajesh Kumar",
    contractorId: "ct_01",
    contractorName: "Samarth Logistics",
    status: "in_transit",
    warehouseId: "wh_mum_01",
    warehouseName: "Bhiwandi Hub",
    totalStops: 4,
    confirmedStops: 2,
    departedAt: hoursAgo(5),
    plannedReturn: hoursAgo(-7),
    stops: [
      {
        id: "stp_01_1",
        stopOrder: 1,
        dealerName: "Shree Balaji Traders",
        city: "Thane",
        invoiceCount: 3,
        invoiceNumbers: ["INV-8821", "INV-8822", "INV-8823"],
        deliveryMode: "secure",
        status: "confirmed",
        confirmedAt: hoursAgo(3),
        dwellMinutes: 22,
      },
      {
        id: "stp_01_2",
        stopOrder: 2,
        dealerName: "Maharaja Retail",
        city: "Kalyan",
        invoiceCount: 2,
        invoiceNumbers: ["INV-8824", "INV-8825"],
        deliveryMode: "simple",
        status: "confirmed",
        confirmedAt: hoursAgo(1.5),
        dwellMinutes: 18,
      },
      {
        id: "stp_01_3",
        stopOrder: 3,
        dealerName: "New Vasai Dealers",
        city: "Vasai",
        invoiceCount: 4,
        invoiceNumbers: ["INV-8826", "INV-8827", "INV-8828", "INV-8829"],
        deliveryMode: "secure",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
      {
        id: "stp_01_4",
        stopOrder: 4,
        dealerName: "Virar Supermarket",
        city: "Virar",
        invoiceCount: 3,
        invoiceNumbers: ["INV-8830", "INV-8831", "INV-8832"],
        deliveryMode: "simple",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
    ],
  },
  {
    id: "trp_02",
    tripCode: "TRP-20260415-0143",
    vehicleId: "veh_02",
    vehicleReg: "MH 12 LK 9982",
    driverId: "drv_04",
    driverName: "Vinod Patil",
    contractorId: "ct_02",
    contractorName: "Adarsh Roadways",
    status: "in_transit",
    warehouseId: "wh_itc_bengaluru",
    warehouseName: "Bhiwandi Hub",
    totalStops: 3,
    confirmedStops: 1,
    departedAt: hoursAgo(2),
    plannedReturn: hoursAgo(-9),
    stops: [
      {
        id: "stp_02_1",
        stopOrder: 1,
        dealerName: "Shivam Traders",
        city: "Andheri",
        invoiceCount: 2,
        invoiceNumbers: ["INV-9001", "INV-9002"],
        deliveryMode: "secure",
        status: "confirmed",
        confirmedAt: hoursAgo(0.5),
        dwellMinutes: 14,
      },
      {
        id: "stp_02_2",
        stopOrder: 2,
        dealerName: "Global Mart",
        city: "Borivali",
        invoiceCount: 3,
        invoiceNumbers: ["INV-9003", "INV-9004", "INV-9005"],
        deliveryMode: "secure",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
      {
        id: "stp_02_3",
        stopOrder: 3,
        dealerName: "Prime Distributors",
        city: "Malad",
        invoiceCount: 1,
        invoiceNumbers: ["INV-9006"],
        deliveryMode: "simple",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
    ],
  },
  {
    id: "trp_03",
    tripCode: "TRP-20260415-0131",
    vehicleId: "veh_04",
    vehicleReg: "KA 05 MN 6601",
    driverId: "drv_06",
    driverName: "Karthik Subramani",
    contractorId: "ct_01",
    contractorName: "Samarth Logistics",
    status: "returning",
    warehouseId: "wh_blr_01",
    warehouseName: "Hoskote FC",
    totalStops: 5,
    confirmedStops: 4,
    departedAt: hoursAgo(9),
    plannedReturn: hoursAgo(-2),
    stops: [
      {
        id: "stp_03_1",
        stopOrder: 1,
        dealerName: "Indiranagar Traders",
        city: "Bengaluru",
        invoiceCount: 2,
        invoiceNumbers: ["INV-7701", "INV-7702"],
        deliveryMode: "secure",
        status: "confirmed",
        confirmedAt: hoursAgo(8),
        dwellMinutes: 10,
      },
      {
        id: "stp_03_2",
        stopOrder: 2,
        dealerName: "Whitefield Cash&Carry",
        city: "Bengaluru",
        invoiceCount: 4,
        invoiceNumbers: ["INV-7703", "INV-7704", "INV-7705", "INV-7706"],
        deliveryMode: "secure",
        status: "confirmed",
        confirmedAt: hoursAgo(7),
        dwellMinutes: 24,
      },
      {
        id: "stp_03_3",
        stopOrder: 3,
        dealerName: "Electronic City Marts",
        city: "Bengaluru",
        invoiceCount: 3,
        invoiceNumbers: ["INV-7707", "INV-7708", "INV-7709"],
        deliveryMode: "simple",
        status: "confirmed",
        confirmedAt: hoursAgo(5),
        dwellMinutes: 16,
      },
      {
        id: "stp_03_4",
        stopOrder: 4,
        dealerName: "Koramangala Depot",
        city: "Bengaluru",
        invoiceCount: 2,
        invoiceNumbers: ["INV-7710", "INV-7711"],
        deliveryMode: "secure",
        status: "confirmed",
        confirmedAt: hoursAgo(3),
        dwellMinutes: 12,
      },
      {
        id: "stp_03_5",
        stopOrder: 5,
        dealerName: "Sarjapur Freshmart",
        city: "Bengaluru",
        invoiceCount: 1,
        invoiceNumbers: ["INV-7712"],
        deliveryMode: "simple",
        status: "disputed",
        confirmedAt: null,
        dwellMinutes: null,
      },
    ],
  },
  {
    id: "trp_04",
    tripCode: "TRP-20260415-0148",
    vehicleId: "veh_05",
    vehicleReg: "TN 18 XY 4410",
    driverId: "drv_05",
    driverName: "Harpreet Singh",
    contractorId: "ct_05",
    contractorName: "Laxmi Freight",
    status: "planned",
    warehouseId: "wh_chn_01",
    warehouseName: "Sriperumbudur",
    totalStops: 2,
    confirmedStops: 0,
    departedAt: null,
    plannedReturn: null,
    stops: [
      {
        id: "stp_04_1",
        stopOrder: 1,
        dealerName: "Mount Road Mart",
        city: "Chennai",
        invoiceCount: 5,
        invoiceNumbers: [],
        deliveryMode: "secure",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
      {
        id: "stp_04_2",
        stopOrder: 2,
        dealerName: "Velachery Superstore",
        city: "Chennai",
        invoiceCount: 3,
        invoiceNumbers: [],
        deliveryMode: "simple",
        status: "pending",
        confirmedAt: null,
        dwellMinutes: null,
      },
    ],
  },
];

// ── Gate events (live/historical) ───────────────────────────────
export const gateEvents: GateEvent[] = [
  {
    id: "ge_01",
    eventType: "outbound_exit",
    vehicleReg: "MH 04 GA 1234",
    personName: "Rajesh Kumar",
    contractor: "Samarth Logistics",
    guardName: "Rahul Patil",
    time: hoursAgo(5),
    status: "exited",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_02",
    eventType: "inbound_entry",
    vehicleReg: "HR 55 AB 8821",
    personName: "Mohd. Faizal",
    contractor: "BlueArrow Transport",
    guardName: "Rahul Patil",
    time: hoursAgo(2.5),
    status: "inside",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_03",
    eventType: "visitor_entry",
    vehicleReg: null,
    personName: "Deepa Menon",
    contractor: null,
    guardName: "Rahul Patil",
    time: hoursAgo(1.75),
    status: "inside",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_04",
    eventType: "contractor_entry",
    vehicleReg: "MH 47 PK 2020",
    personName: "Sachin Bhosale",
    contractor: "Hi-Tech Carriers",
    guardName: "Rahul Patil",
    time: hoursAgo(1.2),
    status: "inside",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_05",
    eventType: "outbound_entry",
    vehicleReg: "MH 12 LK 9982",
    personName: "Vinod Patil",
    contractor: "Adarsh Roadways",
    guardName: "Rahul Patil",
    time: hoursAgo(2.1),
    status: "exited",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_06",
    eventType: "outbound_exit",
    vehicleReg: "MH 12 LK 9982",
    personName: "Vinod Patil",
    contractor: "Adarsh Roadways",
    guardName: "Rahul Patil",
    time: hoursAgo(2),
    status: "exited",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_07",
    eventType: "inbound_entry",
    vehicleReg: "GJ 01 RT 7712",
    personName: "Arjun Deshmukh",
    contractor: "BlueArrow Transport",
    guardName: "Rahul Patil",
    time: minutesAgo(38),
    status: "inside",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
  {
    id: "ge_08",
    eventType: "visitor_entry",
    vehicleReg: null,
    personName: "Rohan Iyer",
    contractor: null,
    guardName: "Rahul Patil",
    time: minutesAgo(12),
    status: "inside",
    warehouseId: "wh_mum_01",
    photoUrl: null,
  },
];

// ── Visitors (currently inside) ─────────────────────────────────
export const visitors: VisitorEntry[] = [
  {
    id: "vis_01",
    visitorType: "visitor",
    fullName: "Deepa Menon",
    hostName: "Ankit Bhatia",
    purpose: "Commercial review",
    passNumber: "V-2041",
    entryTime: hoursAgo(1.75),
    expectedExit: hoursAgo(-0.25),
    vehicleNumber: null,
  },
  {
    id: "vis_02",
    visitorType: "contractor",
    fullName: "Sachin Bhosale",
    hostName: "Priya Nair",
    purpose: "Rack maintenance",
    passNumber: "C-1122",
    entryTime: hoursAgo(1.2),
    expectedExit: hoursAgo(-3),
    vehicleNumber: "MH 47 PK 2020",
  },
  {
    id: "vis_03",
    visitorType: "visitor",
    fullName: "Rohan Iyer",
    hostName: "Rahul Patil",
    purpose: "Safety audit",
    passNumber: "V-2042",
    entryTime: minutesAgo(12),
    expectedExit: hoursAgo(-4),
    vehicleNumber: null,
  },
  {
    id: "vis_04",
    visitorType: "auditor",
    fullName: "CA Nisha Rao",
    hostName: "Manoj Verma",
    purpose: "Quarterly stock audit",
    passNumber: "A-0091",
    entryTime: hoursAgo(3),
    expectedExit: hoursAgo(-1),
    vehicleNumber: null,
  },
];

// ── Alerts (open) ───────────────────────────────────────────────
export const alerts: Alert[] = [
  {
    id: "al_01",
    type: "face_mismatch",
    severity: "critical",
    status: "open",
    message: "Face match 42% below threshold on return of trip TRP-20260415-0131",
    warehouseName: "Hoskote FC",
    entityType: "gate_event",
    entityId: "ge_h1",
    createdAt: minutesAgo(4),
    acknowledgedAt: null,
  },
  {
    id: "al_02",
    type: "pin_locked",
    severity: "critical",
    status: "open",
    message: "PIN locked after 3 wrong attempts at Sarjapur Freshmart (Stop 5)",
    warehouseName: "Hoskote FC",
    entityType: "trip_stop",
    entityId: "stp_03_5",
    createdAt: minutesAgo(9),
    acknowledgedAt: null,
  },
  {
    id: "al_03",
    type: "dl_expiring",
    severity: "warning",
    status: "open",
    message: "DL for Suresh Yadav (DL09…4982) expires in 42 days",
    warehouseName: "Gurugram DC",
    entityType: "driver",
    entityId: "drv_02",
    createdAt: hoursAgo(1.2),
    acknowledgedAt: null,
  },
  {
    id: "al_04",
    type: "vehicle_expired",
    severity: "critical",
    status: "open",
    message: "RC expired 5 days ago for HR 55 AB 8821 (BlueArrow Transport)",
    warehouseName: "Gurugram DC",
    entityType: "vehicle",
    entityId: "veh_03",
    createdAt: hoursAgo(2),
    acknowledgedAt: null,
  },
  {
    id: "al_05",
    type: "bg_flagged",
    severity: "critical",
    status: "open",
    message: "Background check flagged: Mohd. Faizal — criminal record mismatch",
    warehouseName: "Bhiwandi Hub",
    entityType: "driver",
    entityId: "drv_03",
    createdAt: hoursAgo(3),
    acknowledgedAt: null,
  },
  {
    id: "al_06",
    type: "delivery_overdue",
    severity: "warning",
    status: "open",
    message: "Stop 3 (Vasai) unconfirmed for 2h 14m — SLA breach imminent",
    warehouseName: "Bhiwandi Hub",
    entityType: "trip_stop",
    entityId: "stp_01_3",
    createdAt: minutesAgo(22),
    acknowledgedAt: null,
  },
  {
    id: "al_07",
    type: "visitor_overdue",
    severity: "warning",
    status: "open",
    message: "Visitor Deepa Menon exceeded expected exit by 15m",
    warehouseName: "Bhiwandi Hub",
    entityType: "visitor",
    entityId: "vis_01",
    createdAt: minutesAgo(15),
    acknowledgedAt: null,
  },
  {
    id: "al_08",
    type: "contract_expiring",
    severity: "info",
    status: "acknowledged",
    message: "Adarsh Roadways contract expires in 22 days",
    warehouseName: "Multi",
    entityType: "contractor",
    entityId: "ct_02",
    createdAt: hoursAgo(6),
    acknowledgedAt: hoursAgo(5),
  },
];

// ── Incidents ───────────────────────────────────────────────────
export const incidents: Incident[] = [
  {
    id: "inc_01",
    type: "face_mismatch",
    description: "Driver return face mismatch on TRP-20260415-0131",
    warehouseName: "Hoskote FC",
    status: "investigating",
    assignedTo: "Ankit Bhatia",
    slaDeadline: hoursAgo(-6),
    raisedBy: "Rahul Patil",
    createdAt: minutesAgo(4),
    linkedTripCode: "TRP-20260415-0131",
    linkedAlertId: "al_01",
    evidenceCount: 3,
  },
  {
    id: "inc_02",
    type: "fake_pod",
    description: "PIN lock + dealer denies receiving 1 invoice",
    warehouseName: "Hoskote FC",
    status: "open",
    assignedTo: null,
    slaDeadline: hoursAgo(-22),
    raisedBy: "Rahul Patil",
    createdAt: minutesAgo(9),
    linkedTripCode: "TRP-20260415-0131",
    linkedAlertId: "al_02",
    evidenceCount: 2,
  },
  {
    id: "inc_03",
    type: "vehicle_noncompliance",
    description: "RC expired vehicle HR 55 AB 8821 entered main yard",
    warehouseName: "Gurugram DC",
    status: "open",
    assignedTo: "Priya Nair",
    slaDeadline: hoursAgo(-3),
    raisedBy: "Ramesh Gupta",
    createdAt: hoursAgo(2),
    linkedAlertId: "al_04",
    evidenceCount: 1,
  },
  {
    id: "inc_04",
    type: "invoice_mismatch",
    description: "2 invoices entered at gate not found in SuperProcure plan",
    warehouseName: "Bhiwandi Hub",
    status: "investigating",
    assignedTo: "Ankit Bhatia",
    slaDeadline: hoursAgo(-4),
    raisedBy: "Rahul Patil",
    createdAt: hoursAgo(1.2),
    linkedTripCode: "TRP-20260415-0142",
    evidenceCount: 4,
  },
  {
    id: "inc_05",
    type: "driver_noncompliance",
    description: "Driver attempted entry with expired DL (40d past)",
    warehouseName: "Dankuni Hub",
    status: "open",
    assignedTo: null,
    slaDeadline: hoursAgo(-12),
    raisedBy: "Bikash Das",
    createdAt: hoursAgo(3.5),
    evidenceCount: 2,
  },
  {
    id: "inc_06",
    type: "unauthorized_entry",
    description: "Visitor pass V-2041 tailgated into dispatch bay",
    warehouseName: "Bhiwandi Hub",
    status: "resolved",
    assignedTo: "Ankit Bhatia",
    slaDeadline: hoursAgo(5),
    raisedBy: "Rahul Patil",
    createdAt: hoursAgo(8),
    evidenceCount: 1,
    resolutionNote:
      "CCTV review confirmed accidental tailgate. Verbal warning issued to visitor. Escort policy refreshed at gate.",
    closedAt: hoursAgo(2),
  },
  {
    id: "inc_07",
    type: "fraud_attempt",
    description: "Suspicious PIN attempts from non-registered number",
    warehouseName: "Sriperumbudur",
    status: "closed",
    assignedTo: "Balaji K",
    slaDeadline: hoursAgo(22),
    raisedBy: "Balaji K",
    createdAt: hoursAgo(26),
    evidenceCount: 2,
    resolutionNote: "Dealer confirmed wrong mobile number saved. No fraud.",
    closedAt: hoursAgo(10),
  },
  {
    id: "inc_08",
    type: "theft",
    description: "3 missing invoices on return — goods unaccounted",
    warehouseName: "Medchal DC",
    status: "investigating",
    assignedTo: "Lakshmi Rao",
    slaDeadline: hoursAgo(-18),
    raisedBy: "Lakshmi Rao",
    createdAt: hoursAgo(14),
    evidenceCount: 5,
  },
  {
    id: "inc_09",
    type: "face_mismatch",
    description: "Exit face score 58% on MH 12 LK 9982 return — confirmed mismatch",
    warehouseName: "Bhiwandi Hub",
    status: "open",
    assignedTo: null,
    slaDeadline: hoursAgo(-2),
    raisedBy: "Rahul Patil",
    createdAt: minutesAgo(42),
    linkedTripCode: "TRP-20260415-0143",
    linkedAlertId: "al_01",
    evidenceCount: 2,
  },
  {
    id: "inc_10",
    type: "invoice_mismatch",
    description: "Stop 3 (New Vasai Dealers) — dealer disputes 1 of 4 invoices",
    warehouseName: "Bhiwandi Hub",
    status: "investigating",
    assignedTo: "Ankit Bhatia",
    slaDeadline: hoursAgo(-1),
    raisedBy: "Rahul Patil",
    createdAt: hoursAgo(2.5),
    linkedTripCode: "TRP-20260415-0142",
    evidenceCount: 3,
  },
  {
    id: "inc_11",
    type: "vehicle_noncompliance",
    description: "PUC lapsed 3d ago on MH 04 GA 1234 · override granted with 48h grace",
    warehouseName: "Bhiwandi Hub",
    status: "resolved",
    assignedTo: "Ankit Bhatia",
    slaDeadline: hoursAgo(12),
    raisedBy: "Rahul Patil",
    createdAt: hoursAgo(18),
    evidenceCount: 1,
    resolutionNote: "Contractor submitted fresh PUC within 24h. Override audit trail captured.",
    closedAt: hoursAgo(6),
  },
];

// ── Compliance clock (CSO widget) ───────────────────────────────
export const complianceClock: ComplianceBucket = {
  dl_0_30: 7,
  dl_31_60: 12,
  dl_61_90: 18,
  vehicle_0_30: 4,
  vehicle_31_60: 9,
  vehicle_61_90: 11,
  contractor_0_30: 2,
  contractor_31_60: 5,
  contractor_61_90: 3,
};

// ── Compliance expiry detail (/cso/compliance drill-down) ──────
export interface ExpiryRow {
  id: string;
  name: string;
  sub: string; // reg number / DL / contact mobile
  warehouseName: string;
  contractor: string | null;
  expiresOn: Date;
  daysRemaining: number;
}

function row(
  id: string,
  name: string,
  sub: string,
  warehouseName: string,
  contractor: string | null,
  days: number
): ExpiryRow {
  return {
    id,
    name,
    sub,
    warehouseName,
    contractor,
    expiresOn: daysFromNow(days),
    daysRemaining: days,
  };
}

export const expiryDetail = {
  dl: [
    row("e_dl_01", "Mohd. Faizal", "KA01 20190066421", "Hoskote FC", "BlueArrow Transport", 18),
    row("e_dl_02", "Suresh Yadav", "DL09 20170034982", "Gurugram DC", "Adarsh Roadways", 42),
    row("e_dl_03", "Bikram Das", "WB02 20170087790", "Dankuni Hub", "BlueArrow Transport", 55),
    row("e_dl_04", "Ajay Khandelwal", "RJ06 20180044210", "Bhiwadi FC", "Samarth Logistics", 72),
    row("e_dl_05", "Pravin Kale", "MH20 20190011093", "Chakan Logistik", "Laxmi Freight", 81),
    row("e_dl_06", "Nandan Rao", "KA02 20190077310", "Hoskote FC", "Samarth Logistics", 22),
    row("e_dl_07", "Dipankar Sen", "WB05 20170021874", "Dankuni Hub", "BlueArrow Transport", 35),
    row("e_dl_08", "Harpreet Singh", "PB08 20180012990", "Sriperumbudur", "Laxmi Freight", 65),
  ],
  vehicle: [
    row(
      "e_veh_01",
      "HR 55 AB 8821",
      "RC expiry · BlueArrow",
      "Gurugram DC",
      "BlueArrow Transport",
      -5
    ),
    row("e_veh_02", "TS 09 XP 2240", "RC expiry · Laxmi", "Sriperumbudur", "Laxmi Freight", -18),
    row(
      "e_veh_03",
      "MH 12 LK 9982",
      "Insurance · Adarsh",
      "Chakan Logistik",
      "Adarsh Roadways",
      19
    ),
    row("e_veh_04", "GJ 01 RT 7712", "PUC · BlueArrow", "Sanand DC", "BlueArrow Transport", 29),
    row(
      "e_veh_05",
      "UP 16 LM 7520",
      "RC expiry · BlueArrow",
      "Lucknow Hub",
      "BlueArrow Transport",
      34
    ),
    row("e_veh_06", "KL 07 QR 9931", "Fitness · Adarsh", "Hoskote FC", "Adarsh Roadways", 55),
  ],
  contractor: [
    row("e_ct_01", "Orbit Movers", "Ayesha Fernandes", "Multi", null, -7),
    row("e_ct_02", "Adarsh Roadways", "Priya Shah", "Multi", null, 22),
    row("e_ct_03", "Laxmi Freight", "Sunita Joshi", "Multi", null, 55),
  ],
};

// ── Audit events (/cso/audit) ───────────────────────────────────
export interface AuditEntry {
  id: string;
  timestamp: Date;
  actor: string;
  actorRole: string;
  action: string;
  entityType: string;
  entityId: string;
  warehouseName: string;
  ipAddress: string;
  summary: string;
}

export const auditEvents: AuditEntry[] = [
  {
    id: "au_01",
    timestamp: minutesAgo(3),
    actor: "Rahul Patil",
    actorRole: "guard",
    action: "gate_event.create",
    entityType: "gate_event",
    entityId: "ge_2a7f",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.21",
    summary: "Inbound entry · GJ 01 RT 7712 · Arjun Deshmukh",
  },
  {
    id: "au_02",
    timestamp: minutesAgo(8),
    actor: "Ankit Bhatia",
    actorRole: "wh_manager",
    action: "override.compliance",
    entityType: "compliance",
    entityId: "chk_f12d",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.14",
    summary: "DL expiring override · driver drv_05 · reason: 'return trip in 3h'",
  },
  {
    id: "au_03",
    timestamp: minutesAgo(12),
    actor: "Rahul Patil",
    actorRole: "guard",
    action: "trip.depart",
    entityType: "trip",
    entityId: "trp_01",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.21",
    summary: "Confirmed departure · TRP-20260415-0142 · 4 stops",
  },
  {
    id: "au_04",
    timestamp: minutesAgo(22),
    actor: "Balaji K",
    actorRole: "wh_manager",
    action: "alert.acknowledge",
    entityType: "alert",
    entityId: "al_82d",
    warehouseName: "Sriperumbudur",
    ipAddress: "10.18.7.32",
    summary: "Acked face-mismatch alert",
  },
  {
    id: "au_05",
    timestamp: hoursAgo(0.8),
    actor: "Priya Nair",
    actorRole: "wh_manager",
    action: "incident.assign",
    entityType: "incident",
    entityId: "inc_03",
    warehouseName: "Gurugram DC",
    ipAddress: "10.14.2.18",
    summary: "Assigned incident inc_03 to self",
  },
  {
    id: "au_06",
    timestamp: hoursAgo(1.1),
    actor: "dealer:9820032",
    actorRole: "dealer",
    action: "delivery.confirm",
    entityType: "trip_stop",
    entityId: "stp_01_2",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "183.88.14.222",
    summary: "Delivery confirmed · stop 2 · Maharaja Retail",
  },
  {
    id: "au_07",
    timestamp: hoursAgo(1.6),
    actor: "Manoj Verma",
    actorRole: "cso",
    action: "incident.escalate",
    entityType: "incident",
    entityId: "inc_02",
    warehouseName: "Hoskote FC",
    ipAddress: "10.1.1.4",
    summary: "Escalated incident to regional security",
  },
  {
    id: "au_08",
    timestamp: hoursAgo(2.1),
    actor: "Rahul Patil",
    actorRole: "guard",
    action: "contractor.quick_add",
    entityType: "contractor",
    entityId: "ct_07",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.21",
    summary: "Quick-added FastLane 3PL at gate",
  },
  {
    id: "au_09",
    timestamp: hoursAgo(2.5),
    actor: "Ankit Bhatia",
    actorRole: "wh_manager",
    action: "trip.create",
    entityType: "trip",
    entityId: "trp_02",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.14",
    summary: "Created trip TRP-20260415-0143 (manual, POC)",
  },
  {
    id: "au_10",
    timestamp: hoursAgo(3.2),
    actor: "Lakshmi Rao",
    actorRole: "wh_manager",
    action: "driver.update_dl",
    entityType: "driver",
    entityId: "drv_08",
    warehouseName: "Medchal DC",
    ipAddress: "10.16.5.2",
    summary: "Updated DL expiry for Bikram Das",
  },
  {
    id: "au_11",
    timestamp: hoursAgo(4.0),
    actor: "Rahul Patil",
    actorRole: "guard",
    action: "visitor.create",
    entityType: "visitor",
    entityId: "vl_03",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "10.12.4.21",
    summary: "Visitor entry · Rohan Iyer (safety audit)",
  },
  {
    id: "au_12",
    timestamp: hoursAgo(5.3),
    actor: "Manoj Verma",
    actorRole: "cso",
    action: "report.export",
    entityType: "report",
    entityId: "rpt_0881",
    warehouseName: "Multi",
    ipAddress: "10.1.1.4",
    summary: "Exported weekly compliance brief · 14 warehouses",
  },
  {
    id: "au_13",
    timestamp: hoursAgo(6.1),
    actor: "Bikash Das",
    actorRole: "wh_manager",
    action: "incident.open",
    entityType: "incident",
    entityId: "inc_05",
    warehouseName: "Dankuni Hub",
    ipAddress: "10.22.3.11",
    summary: "Raised driver-noncompliance incident",
  },
  {
    id: "au_14",
    timestamp: hoursAgo(7.4),
    actor: "system",
    actorRole: "system",
    action: "alert.escalate",
    entityType: "alert",
    entityId: "al_05",
    warehouseName: "Bhiwandi Hub",
    ipAddress: "127.0.0.1",
    summary: "Auto-escalated bg_flagged alert to CSO (30 min SLA)",
  },
  {
    id: "au_15",
    timestamp: hoursAgo(9),
    actor: "Priya Nair",
    actorRole: "wh_manager",
    action: "vehicle.update_docs",
    entityType: "vehicle",
    entityId: "veh_02",
    warehouseName: "Gurugram DC",
    ipAddress: "10.14.2.18",
    summary: "Re-uploaded insurance PDF for MH 12 LK 9982",
  },
];

// ── Aggregate metrics (role-level) ──────────────────────────────
export const dashboardMetrics = {
  cso: {
    activeTripsPan: 77,
    criticalAlerts: 5,
    slaBreachedWarehouses: 2,
    facematchToday: 142,
    deliveriesConfirmedToday: 284,
    incidentsOpen: 6,
  },
  manager: {
    activeTrips: 14,
    openAlerts: 3,
    driversFlagged: 2,
    visitorsInside: 4,
    deliveriesToday: 46,
    incidentsOpen: 1,
  },
  guard: {
    insideNow: 7,
    outboundToday: 11,
    inboundToday: 8,
    visitorsToday: 12,
  },
};

// ── Advisory Platform — Disruptions ─────────────────────────────

function iso(hoursBack: number): string {
  return new Date(Date.now() - hoursBack * 3600000).toISOString();
}

function isoFuture(hoursForward: number): string {
  return new Date(Date.now() + hoursForward * 3600000).toISOString();
}

export const MOCK_DISRUPTIONS: Disruption[] = [
  {
    id: "dis_01",
    category: "political",
    title: "Bharat Bandh — NH44 blocked at Panipat toll",
    summary: "All-India strike called by coalition parties. NH44 blocked at multiple points in Haryana. Heavy police deployment.",
    detail: "The Bharat Bandh called by the opposition coalition has effectively blocked NH44 at Panipat toll, Karnal bypass, and the Ambala–Shahabad stretch. Protesters are burning tyres on the carriageway. Police are deployed but not dispersing crowds. No vehicle movement for last 4h.",
    impact: "All Delhi–Punjab and Delhi–Himachal trucks are stranded. Estimated 4–8h delay. Consider routing via NH52 Yamuna Expressway or holding vehicles at origin till 18:00 IST.",
    risk: "critical",
    region: "Haryana",
    state: "Haryana",
    highway: "NH44",
    affectedRoutes: ["Delhi–Chandigarh", "Delhi–Amritsar", "Delhi–Himachal"],
    eta_impact_hours: 6,
    verified: true,
    source: "NHAI Alert + Ground Team",
    started_at: iso(4),
    expected_clear_at: isoFuture(4),
  },
  {
    id: "dis_02",
    category: "natural_disaster",
    title: "Cyclone Mandous — Coastal Odisha severely affected",
    summary: "Cyclone Mandous crossed coast near Puri with 120kmph winds. NH16 closed. Flooding on Bhubaneswar–Kolkata corridor.",
    detail: "Cyclone Mandous made landfall near Puri at 02:30 IST. Widespread flooding on NH16, NH316, and SH17. Bridges on Mahanadi basin crossings under water. NDRF deployed. Power outage across 14 districts.",
    impact: "All East Coast corridor dispatches must be held. Bhubaneswar DC operations suspended. Kolkata–Chennai corridor reroute via NH19–Nagpur–Hyderabad adding 18h.",
    risk: "critical",
    region: "Coastal Odisha",
    state: "Odisha",
    highway: "NH16",
    affectedRoutes: ["Kolkata–Chennai", "Bhubaneswar–Hyderabad", "Kolkata–Vizag"],
    eta_impact_hours: 18,
    verified: true,
    source: "IMD Advisory + State EOC",
    started_at: iso(8),
    expected_clear_at: isoFuture(36),
  },
  {
    id: "dis_03",
    category: "security",
    title: "Farmers' agitation — Shambhu border blockade continues",
    summary: "Farmer groups blocking Shambhu border on NH44 for 3rd consecutive day. Convoy movement impossible.",
    detail: "Farmer agitation at Shambhu border (Punjab–Haryana) continues for day 3. Security forces have formed a perimeter. No commercial vehicle permitted. Alternate Bathinda–Hisar route congested but passable.",
    impact: "Punjab-bound freight delayed 4–6h. Use NH7 Bathinda bypass or delay departures till 20:00 IST.",
    risk: "high",
    region: "Punjab–Haryana Border",
    state: "Punjab",
    highway: "NH44",
    affectedRoutes: ["Delhi–Amritsar", "Delhi–Ludhiana", "Delhi–Jalandhar"],
    eta_impact_hours: 5,
    verified: true,
    source: "Punjab Police Control Room",
    started_at: iso(72),
    expected_clear_at: undefined,
  },
  {
    id: "dis_04",
    category: "vvip",
    title: "PM convoy — Mumbai–Pune Expressway partial closure",
    summary: "Prime Minister motorcade scheduled 15:00–17:30 IST. Expressway lanes 1 & 2 closed for security.",
    detail: "SPG has notified a VVIP movement on Mumbai–Pune Expressway (NH48). Lanes 1 and 2 will be cleared from Khopoli to Pune interchange 15:00–17:30 IST. Lane 3 operational for commercial vehicles but at reduced speed (40 kmph max).",
    impact: "ETA delay of 1.5–2.5h for all Mumbai–Pune dispatches during window. Recommend dispatching before 13:00 IST or after 18:00 IST.",
    risk: "high",
    region: "Mumbai–Pune",
    state: "Maharashtra",
    highway: "NH48",
    affectedRoutes: ["Mumbai–Pune", "Mumbai–Bengaluru", "Mumbai–Hyderabad"],
    eta_impact_hours: 2,
    verified: true,
    source: "SPG Notification via Traffic Police",
    started_at: iso(0.5),
    expected_clear_at: isoFuture(4),
  },
  {
    id: "dis_05",
    category: "weather",
    title: "Flash floods — NH66 Ratnagiri stretch underwater",
    summary: "Heavy rainfall (240mm/24h) has submerged NH66 at Ratnagiri district. 8 km stretch impassable.",
    detail: "Konkan coast received 240mm rainfall in 24h. NH66 between Ratnagiri and Rajapur has 8km submerged with water level 1–1.5m in places. Trucks have been stranded since last night. PWD has not commenced repair.",
    impact: "Mumbai–Goa route via coastal NH66 is blocked. Divert via NH48–Kolhapur–Belgaum (adds 3h).",
    risk: "high",
    region: "Konkan",
    state: "Maharashtra",
    highway: "NH66",
    affectedRoutes: ["Mumbai–Goa", "Mumbai–Mangalore"],
    eta_impact_hours: 3,
    verified: true,
    source: "Maharashtra PWD + Field Reports",
    started_at: iso(14),
    expected_clear_at: isoFuture(12),
  },
  {
    id: "dis_06",
    category: "religious",
    title: "Ganesh Chaturthi procession — Bengaluru Ring Road closed",
    summary: "Annual Ganesh immersion procession tonight. BBMP has closed Outer Ring Road 19:00–23:00 IST.",
    detail: "Ganesh Chaturthi immersion processions in Bengaluru will use the Outer Ring Road and Sarjapur–Hosur stretch. BBMP Traffic Police have ordered closure of ORR from Hebbal to Electronic City 19:00–23:00 IST. Alternative: NICE Road.",
    impact: "Hoskote FC to Bengaluru city deliveries should be completed before 18:00 IST or dispatched after 23:30 IST.",
    risk: "medium",
    region: "Bengaluru",
    state: "Karnataka",
    highway: "ORR",
    affectedRoutes: ["Hoskote–Bengaluru City", "Electronic City–Airport"],
    eta_impact_hours: 2,
    verified: true,
    source: "BBMP Traffic Advisory",
    started_at: iso(1),
    expected_clear_at: isoFuture(5),
  },
  {
    id: "dis_07",
    category: "infrastructure",
    title: "Bridge repair — Narmada crossing NH30 single-lane",
    summary: "Emergency repair on Narmada bridge at Hoshangabad. Single-lane operation causing 2–3h queues.",
    detail: "NHAI has commenced emergency re-decking of Narmada bridge on NH30 near Hoshangabad. Traffic reduced to one lane with alternate timing. Queue lengths of 12–15km building on both sides.",
    impact: "Bhopal–Nagpur freight delayed 2–3h. No alternate route available—plan for buffer.",
    risk: "medium",
    region: "Hoshangabad",
    state: "MP",
    highway: "NH30",
    affectedRoutes: ["Bhopal–Nagpur", "Indore–Raipur"],
    eta_impact_hours: 2.5,
    verified: true,
    source: "NHAI Project Office",
    started_at: iso(6),
    expected_clear_at: isoFuture(48),
  },
  {
    id: "dis_08",
    category: "traffic",
    title: "Multi-vehicle accident — NH19 Allahabad bypass",
    summary: "6-vehicle pile-up near Naini bridge. NH19 blocked outbound. Recovery operation ongoing.",
    detail: "A 6-vehicle pile-up involving 2 trucks, 3 cars and a bus occurred near Naini bridge on NH19 at 06:40 IST. One truck has overturned blocking both outbound lanes. NHAI and police are on site. Recovery crane dispatched from Allahabad.",
    impact: "Varanasi and Patna bound freight should use NH96 bypass via Phaphamau. Add 45min.",
    risk: "medium",
    region: "Allahabad",
    state: "Uttar Pradesh",
    highway: "NH19",
    affectedRoutes: ["Kanpur–Varanasi", "Delhi–Patna"],
    eta_impact_hours: 1.5,
    verified: true,
    source: "UP Police PRO",
    started_at: iso(3),
    expected_clear_at: isoFuture(2),
  },
  {
    id: "dis_09",
    category: "weather",
    title: "Dense fog — Yamuna Expressway speed limit 40kmph",
    summary: "Visibility below 50m on Yamuna Expressway early morning. Speed limit reduced. Multiple minor accidents.",
    detail: "IMD has issued dense fog advisory for western UP. Yamuna Expressway visibility dropped below 50m at multiple points. YEIDA has reduced speed limit to 40 kmph. Two minor rear-end collisions already reported.",
    impact: "Agra and Mathura-bound freight will see 1–2h delay. Night dispatches not recommended.",
    risk: "medium",
    region: "Western UP",
    state: "Uttar Pradesh",
    highway: "Yamuna Expressway",
    affectedRoutes: ["Delhi–Agra", "Delhi–Mathura"],
    eta_impact_hours: 1.5,
    verified: true,
    source: "IMD + YEIDA",
    started_at: iso(5),
    expected_clear_at: isoFuture(3),
  },
  {
    id: "dis_10",
    category: "political",
    title: "State bandh — Assam–Meghalaya border tension",
    summary: "Northeast student union called 12h bandh in Assam following border incident. NH37 impacted.",
    detail: "AASU has called a 12h bandh in Lower Assam districts following the Meghalaya border tension. NH37 blocked at Kamrup and Barpeta by agitators. Security forces deployed. No violence reported.",
    impact: "Guwahati Hub dispatches delayed. All NE Corridor freight should hold till bandh lifted.",
    risk: "high",
    region: "Lower Assam",
    state: "Assam",
    highway: "NH37",
    affectedRoutes: ["Guwahati–Silchar", "Guwahati–Tezpur"],
    eta_impact_hours: 6,
    verified: true,
    source: "Assam Police Control Room",
    started_at: iso(2),
    expected_clear_at: isoFuture(8),
  },
  {
    id: "dis_11",
    category: "infrastructure",
    title: "Toll plaza upgrade — Delhi–Jaipur NH48 bottleneck",
    summary: "FASTag integration upgrade at Shahjahanpur toll causing congestion. 45min delay reported.",
    detail: "NHAI is upgrading the FASTag systems at Shahjahanpur toll (KM 163) on NH48. Lane closures during daytime. 6 of 12 lanes operational. Queue of 4km reported.",
    impact: "Jaipur, Ajmer, and Jodhpur dispatches should plan extra 1h buffer during 10:00–17:00 IST window.",
    risk: "low",
    region: "Shahjahanpur",
    state: "Rajasthan",
    highway: "NH48",
    affectedRoutes: ["Delhi–Jaipur", "Delhi–Ajmer"],
    eta_impact_hours: 1,
    verified: true,
    source: "NHAI Toll Ops",
    started_at: iso(1),
    expected_clear_at: isoFuture(24),
  },
  {
    id: "dis_12",
    category: "security",
    title: "Stone pelting incidents — NH44 Srinagar approach",
    summary: "Sporadic stone-pelting incidents reported near Qazigund. J&K Police advisory issued. Night movement restricted.",
    detail: "J&K Police have issued an advisory against night movement on NH44 between Banihal and Qazigund following stone pelting incidents. Three trucks damaged. Daytime convoy movement with police escort recommended.",
    impact: "Kashmir-bound freight must travel only 07:00–17:00 IST with police convoy registration. Contact J&K Traffic Police at checkpoint.",
    risk: "high",
    region: "Banihal–Qazigund",
    state: "J&K",
    highway: "NH44",
    affectedRoutes: ["Jammu–Srinagar"],
    eta_impact_hours: 4,
    verified: true,
    source: "J&K Police PRO",
    started_at: iso(10),
    expected_clear_at: undefined,
  },
];

// ── Advisory Platform — Advisories ──────────────────────────────

export const MOCK_ADVISORIES: Advisory[] = [
  {
    id: "adv_01",
    type: "hold",
    title: "Hold all NH44 northbound dispatches immediately",
    narrative: "Critical blockade on NH44 at Panipat and Shambhu border makes northbound movement impossible. Vehicles stuck on route face 6–10h delay with no clear resolution timeline.",
    recommendedAction: "Hold all Punjab, HP, J&K bound trucks at origin. Monitor 18:00 IST clearance update. Pre-position near dispatch bay for quick release.",
    region: "Haryana / Punjab",
    riskLevel: "critical",
    confidence: 97,
    isUrgent: true,
    validUntil: isoFuture(6),
    disruptionIds: ["dis_01", "dis_03"],
  },
  {
    id: "adv_02",
    type: "reroute",
    title: "Reroute Kolkata–Chennai via Nagpur to avoid cyclone",
    narrative: "Cyclone Mandous has rendered NH16 East Coast corridor impassable for 36h+. The inland route via NH19–NH44–Nagpur–Hyderabad adds 18h but is the only viable alternative.",
    recommendedAction: "Issue reroute order to all active East Coast trucks. Update ETA at delivery stops by +18h. Notify dealers at Vizag and Chennai of delay.",
    region: "Odisha / Andhra Pradesh",
    riskLevel: "critical",
    confidence: 95,
    isUrgent: true,
    validUntil: isoFuture(36),
    disruptionIds: ["dis_02"],
  },
  {
    id: "adv_03",
    type: "dispatch_early",
    title: "Dispatch Mumbai–Pune before 13:00 IST to beat VVIP closure",
    narrative: "VVIP movement on NH48 will close expressway lanes 15:00–17:30 IST. Trucks dispatched before 13:00 IST clear the corridor before restrictions apply.",
    recommendedAction: "Advance Mumbai–Pune departure to before 13:00 IST. If not possible, hold and dispatch after 18:00 IST. Communicate ETA adjustments to Pune warehouse.",
    region: "Mumbai–Pune",
    riskLevel: "high",
    confidence: 92,
    isUrgent: true,
    validUntil: isoFuture(3),
    disruptionIds: ["dis_04"],
  },
  {
    id: "adv_04",
    type: "reroute",
    title: "Divert Mumbai–Goa via Kolhapur — NH66 flooded",
    narrative: "Flash flooding on NH66 Ratnagiri adds 3h to coastal route. The Kolhapur–Belgaum–Panaji alternate via NH48 and NH4A is clear and adds only modest distance.",
    recommendedAction: "Update driver routing to NH48 → Kolhapur → Belgaum → Panaji. Confirm driver has updated maps. ETA push of +3h.",
    region: "Konkan",
    riskLevel: "high",
    confidence: 89,
    isUrgent: false,
    validUntil: isoFuture(12),
    disruptionIds: ["dis_05"],
  },
  {
    id: "adv_05",
    type: "avoid_night",
    title: "Avoid night dispatch on Yamuna Expressway — dense fog",
    narrative: "IMD dense fog advisory for western UP is forecast till 09:00 IST tomorrow. Visibility < 50m increases accident risk significantly on Yamuna Expressway.",
    recommendedAction: "Suspend night departures to Agra/Mathura. Schedule all such dispatches after 09:00 IST when fog is expected to clear. Add 2h ETA buffer for early morning runs.",
    region: "Western UP",
    riskLevel: "medium",
    confidence: 88,
    isUrgent: false,
    validUntil: isoFuture(10),
    disruptionIds: ["dis_09"],
  },
  {
    id: "adv_06",
    type: "delay",
    title: "Delay Bengaluru city dispatches — procession tonight",
    narrative: "Ganesh procession closes ORR 19:00–23:00 IST. Dispatches from Hoskote FC after 16:30 IST will be caught in procession traffic.",
    recommendedAction: "Complete all Bengaluru city deliveries by 17:30 IST. Remaining loads depart after 23:30 IST when ORR reopens.",
    region: "Bengaluru",
    riskLevel: "medium",
    confidence: 96,
    isUrgent: false,
    validUntil: isoFuture(8),
    disruptionIds: ["dis_06"],
  },
  {
    id: "adv_07",
    type: "delay",
    title: "Add 3h buffer for Bhopal–Nagpur — Narmada bridge single-lane",
    narrative: "Emergency bridge repair on NH30 is causing 2–3h queues. No alternative route. Delay is unavoidable but manageable with pre-communication to receiving warehouses.",
    recommendedAction: "Update ETA by +3h for Nagpur-bound freight from Bhopal. Notify Nagpur FC receiving team. Consider splitting load across two dispatch windows to reduce queue impact.",
    region: "MP",
    riskLevel: "medium",
    confidence: 85,
    isUrgent: false,
    validUntil: isoFuture(48),
    disruptionIds: ["dis_07"],
  },
  {
    id: "adv_08",
    type: "split_shipment",
    title: "Split Guwahati Hub load — Assam bandh in progress",
    narrative: "12h bandh in Lower Assam blocks outbound movement from Guwahati Hub. Splitting loads across two shifts (post-bandh) reduces detention risk and avoids SLA breach on next-day deliveries.",
    recommendedAction: "Hold all outbound trucks at Guwahati Hub. Plan 2 dispatch waves post-bandh: 1st wave at 22:00 IST for nearby routes, 2nd wave at 06:00 IST tomorrow for longer routes.",
    region: "Assam",
    riskLevel: "high",
    confidence: 91,
    isUrgent: false,
    validUntil: isoFuture(12),
    disruptionIds: ["dis_10"],
  },
];

// ── Advisory Platform — Region Risks ────────────────────────────

export const MOCK_REGION_RISKS: RegionRisk[] = [
  { region: "Haryana",             state: "Haryana",           riskLevel: "critical", activeDisruptions: 2, keyIssue: "Bharat Bandh + border blockade" },
  { region: "Coastal Odisha",      state: "Odisha",            riskLevel: "critical", activeDisruptions: 1, keyIssue: "Cyclone Mandous — corridor closed" },
  { region: "Punjab–Haryana Belt", state: "Punjab",            riskLevel: "high",     activeDisruptions: 1, keyIssue: "Farmer agitation at Shambhu border" },
  { region: "Mumbai–Pune",         state: "Maharashtra",       riskLevel: "high",     activeDisruptions: 2, keyIssue: "VVIP movement + NH66 flooding" },
  { region: "Banihal–Qazigund",    state: "J&K",               riskLevel: "high",     activeDisruptions: 1, keyIssue: "Security — night movement restricted" },
  { region: "Lower Assam",         state: "Assam",             riskLevel: "high",     activeDisruptions: 1, keyIssue: "State bandh — NH37 blocked" },
  { region: "Western UP",          state: "Uttar Pradesh",     riskLevel: "medium",   activeDisruptions: 2, keyIssue: "Dense fog + NH19 accident" },
  { region: "Bengaluru",           state: "Karnataka",         riskLevel: "medium",   activeDisruptions: 1, keyIssue: "Ganesh procession — ORR closure" },
  { region: "Hoshangabad",         state: "MP",                riskLevel: "medium",   activeDisruptions: 1, keyIssue: "Bridge repair — single lane" },
  { region: "Delhi–Jaipur",        state: "Rajasthan",         riskLevel: "low",      activeDisruptions: 1, keyIssue: "Toll upgrade bottleneck" },
  { region: "Tamil Nadu",          state: "Tamil Nadu",        riskLevel: "safe",     activeDisruptions: 0, keyIssue: "No active disruptions" },
  { region: "Gujarat",             state: "Gujarat",           riskLevel: "safe",     activeDisruptions: 0, keyIssue: "Corridors clear" },
];

// ── Advisory Platform — Dashboard Stats ─────────────────────────

export const MOCK_STATS = {
  totalDisruptions:  MOCK_DISRUPTIONS.length,
  criticalAlerts:    MOCK_DISRUPTIONS.filter((d) => d.risk === "critical").length,
  highRiskCorridors: MOCK_DISRUPTIONS.filter((d) => d.risk === "critical" || d.risk === "high").length,
  safeCorriders:     MOCK_REGION_RISKS.filter((r) => r.riskLevel === "safe").length,
  pendingAdvisories: MOCK_ADVISORIES.filter((a) => a.isUrgent).length,
  regionsAffected:   MOCK_REGION_RISKS.filter((r) => r.riskLevel !== "safe").length,
};

// ── Advisory Platform — Route Analysis reference data ───────────

export const MAJOR_CITIES = [
  "Mumbai", "Delhi", "Bengaluru", "Chennai", "Hyderabad",
  "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow",
  "Surat", "Nagpur", "Indore", "Bhopal", "Patna",
  "Coimbatore", "Kochi", "Chandigarh", "Guwahati", "Bhubaneswar",
  "Visakhapatnam", "Amritsar", "Varanasi", "Agra", "Jodhpur",
];

export const VEHICLE_TYPES = [
  "9-T Box Truck",
  "14-T Container",
  "22-T Trailer",
  "32-T Multi-axle",
  "9-T Reefer",
  "Mini Truck (3.5T)",
  "Tanker",
];

export const CARGO_TYPES = [
  "FMCG / Consumer Goods",
  "Pharma / Cold Chain",
  "Industrial / Machinery",
  "Hazardous / Chemical",
  "Perishables",
  "Electronics",
  "Auto Parts",
  "Construction Material",
];

// ── Pre-Planning — Dispatch Plans ────────────────────────────────

export const MOCK_DISPATCH_PLANS: DispatchPlan[] = [
  {
    id: "plan_01",
    origin: "Mumbai",
    destination: "Chandigarh",
    vehicleType: "22-T Trailer",
    cargoType: "FMCG / Consumer Goods",
    plannedDate: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    plannedTime: "06:00",
    notes: "Priority FMCG load — dealer committed delivery by 20:00 IST",
    riskScore: 82,
    riskLevel: "critical",
    recommendation: "hold",
    etaImpactHours: 8,
    safeWindowFrom: isoFuture(30),
    safeWindowTo: isoFuture(38),
    affectedDisruptionIds: ["dis_01", "dis_03"],
    alternativeRoutes: [
      { label: "NH52 Yamuna Expressway bypass", via: "Agra–Mathura–Saharanpur", extraKm: 42, extraHours: 1.5, riskLevel: "medium", riskScore: 45 },
      { label: "Hold till bandh clears", via: "Original NH44 after 18:00 IST", extraKm: 0, extraHours: 8, riskLevel: "low", riskScore: 20 },
    ],
    aiNarrative: "Both NH44 blockades (Bharat Bandh + Shambhu farmer agitation) will make the Delhi–Chandigarh corridor impassable for the next 6–10h. A 06:00 IST dispatch today is high risk. The safest option is to hold the truck and dispatch after 18:00 IST when the bandh is expected to lift. If SLA is critical, route via NH52 through Yamuna Expressway and Saharanpur, adding ~1.5h but avoiding the blockade entirely.",
    status: "on_hold",
    createdAt: iso(3),
    approvedBy: undefined,
  },
  {
    id: "plan_02",
    origin: "Mumbai",
    destination: "Pune",
    vehicleType: "14-T Container",
    cargoType: "Electronics",
    plannedDate: new Date().toISOString().slice(0, 10),
    plannedTime: "12:30",
    notes: "Electronics consignment for Pune DC replenishment",
    riskScore: 68,
    riskLevel: "high",
    recommendation: "dispatch_early",
    etaImpactHours: 2,
    safeWindowFrom: iso(0),
    safeWindowTo: isoFuture(1),
    affectedDisruptionIds: ["dis_04"],
    alternativeRoutes: [
      { label: "Dispatch before 13:00 IST", via: "NH48 Expressway (clear window)", extraKm: 0, extraHours: 0, riskLevel: "low", riskScore: 15 },
      { label: "Dispatch after 18:00 IST", via: "NH48 post-VVIP window", extraKm: 0, extraHours: 6, riskLevel: "low", riskScore: 18 },
    ],
    aiNarrative: "VVIP movement on NH48 between 15:00–17:30 IST will reduce expressway capacity significantly. Your planned 12:30 departure is borderline — traffic builds from 14:00 IST. Recommend pushing departure to 12:00 sharp to clear Pune interchange before the window. If loading isn't complete, hold and dispatch after 18:00 IST.",
    status: "approved",
    createdAt: iso(5),
    approvedBy: "Manoj Verma",
  },
  {
    id: "plan_03",
    origin: "Bengaluru",
    destination: "Chennai",
    vehicleType: "14-T Container",
    cargoType: "FMCG / Consumer Goods",
    plannedDate: new Date().toISOString().slice(0, 10),
    plannedTime: "09:00",
    notes: "",
    riskScore: 22,
    riskLevel: "safe",
    recommendation: "dispatch",
    etaImpactHours: 0,
    safeWindowFrom: iso(2),
    safeWindowTo: isoFuture(16),
    affectedDisruptionIds: [],
    alternativeRoutes: [],
    aiNarrative: "No active disruptions on the Bengaluru–Chennai NH48 / NH44 corridor. Road conditions are clear. Dispatch as planned at 09:00 IST. ETA Chennai ~15:30 IST assuming standard transit.",
    status: "dispatched",
    createdAt: iso(18),
    approvedBy: "Karthik S",
  },
  {
    id: "plan_04",
    origin: "Delhi",
    destination: "Amritsar",
    vehicleType: "9-T Box Truck",
    cargoType: "Pharma / Cold Chain",
    plannedDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
    plannedTime: "04:00",
    notes: "Temperature-sensitive pharma — must reach before 14:00 to maintain cold chain",
    riskScore: 76,
    riskLevel: "high",
    recommendation: "reroute",
    etaImpactHours: 5,
    safeWindowFrom: isoFuture(20),
    safeWindowTo: isoFuture(28),
    affectedDisruptionIds: ["dis_01", "dis_03"],
    alternativeRoutes: [
      { label: "NH52 via Saharanpur–Pathankot", via: "NH52 → NH44 north of blockade", extraKm: 55, extraHours: 1.5, riskLevel: "medium", riskScore: 40 },
      { label: "Wait and depart 20:00 IST", via: "NH44 after bandh clears", extraKm: 0, extraHours: 16, riskLevel: "low", riskScore: 22 },
    ],
    aiNarrative: "Cold chain shipment to Amritsar faces two simultaneous blockades on NH44. A 04:00 IST departure tomorrow risks arriving at the Panipat blockade at 07:00 IST when protests are most intense. Strongly recommend NH52 via Saharanpur as the reroute — it adds 55km but avoids both disruption zones. Notify cold chain driver about alternate GPS route before departure.",
    status: "draft",
    createdAt: iso(1),
  },
  {
    id: "plan_05",
    origin: "Kolkata",
    destination: "Bhubaneswar",
    vehicleType: "22-T Trailer",
    cargoType: "Industrial / Machinery",
    plannedDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
    plannedTime: "08:00",
    notes: "Heavy machinery — slow transit, needs clear roads",
    riskScore: 91,
    riskLevel: "critical",
    recommendation: "hold",
    etaImpactHours: 36,
    safeWindowFrom: isoFuture(60),
    safeWindowTo: isoFuture(72),
    affectedDisruptionIds: ["dis_02"],
    alternativeRoutes: [
      { label: "Via NH19–Nagpur–Hyderabad (inland)", via: "NH19 → NH44 → NH65", extraKm: 480, extraHours: 18, riskLevel: "medium", riskScore: 38 },
      { label: "Hold 36h for cyclone clearance", via: "NH16 post-clearance", extraKm: 0, extraHours: 36, riskLevel: "low", riskScore: 20 },
    ],
    aiNarrative: "Cyclone Mandous has made NH16 East Coast corridor completely impassable. Flooding is expected to persist for 36h+. A heavy machinery truck cannot risk the inland detour (480km extra, 18h). Recommend holding the dispatch for 36h until NDRF clears the route. Update the Bhubaneswar DC and adjust receiving slot accordingly.",
    status: "on_hold",
    createdAt: iso(6),
  },
  {
    id: "plan_06",
    origin: "Hyderabad",
    destination: "Nagpur",
    vehicleType: "9-T Box Truck",
    cargoType: "Auto Parts",
    plannedDate: new Date().toISOString().slice(0, 10),
    plannedTime: "07:00",
    notes: "",
    riskScore: 35,
    riskLevel: "low",
    recommendation: "dispatch",
    etaImpactHours: 0.5,
    safeWindowFrom: iso(1),
    safeWindowTo: isoFuture(12),
    affectedDisruptionIds: ["dis_07"],
    alternativeRoutes: [],
    aiNarrative: "Minor delay possible due to Narmada bridge single-lane operation near Hoshangabad, adding ~30min. No significant risk on this corridor. Dispatch as planned. Inform driver of the bridge bottleneck and suggest early morning passage (before 09:00 IST) to beat queue build-up.",
    status: "dispatched",
    createdAt: iso(12),
    approvedBy: "Lakshmi Rao",
  },
];

// ── Pre-Planning — Monitored Corridors ───────────────────────────

export const MOCK_CORRIDORS: MonitoredCorridor[] = [
  {
    id: "cor_01",
    name: "Delhi–Chandigarh",
    origin: "Delhi",
    destination: "Chandigarh",
    highway: "NH44",
    distanceKm: 265,
    riskLevel: "critical",
    activeDisruptions: 2,
    lastChecked: iso(0.25),
    alertsEnabled: true,
    tags: ["High frequency", "Punjab corridor"],
  },
  {
    id: "cor_02",
    name: "Mumbai–Pune",
    origin: "Mumbai",
    destination: "Pune",
    highway: "NH48",
    distanceKm: 150,
    riskLevel: "high",
    activeDisruptions: 1,
    lastChecked: iso(0.5),
    alertsEnabled: true,
    tags: ["Daily dispatch", "Express route"],
  },
  {
    id: "cor_03",
    name: "Kolkata–Bhubaneswar",
    origin: "Kolkata",
    destination: "Bhubaneswar",
    highway: "NH16",
    distanceKm: 441,
    riskLevel: "critical",
    activeDisruptions: 1,
    lastChecked: iso(0.1),
    alertsEnabled: true,
    tags: ["East Coast", "Cyclone zone"],
  },
  {
    id: "cor_04",
    name: "Bengaluru–Chennai",
    origin: "Bengaluru",
    destination: "Chennai",
    highway: "NH48",
    distanceKm: 346,
    riskLevel: "safe",
    activeDisruptions: 0,
    lastChecked: iso(1),
    alertsEnabled: true,
    tags: ["South corridor", "High volume"],
  },
  {
    id: "cor_05",
    name: "Delhi–Agra",
    origin: "Delhi",
    destination: "Agra",
    highway: "Yamuna Expressway",
    distanceKm: 205,
    riskLevel: "medium",
    activeDisruptions: 1,
    lastChecked: iso(0.75),
    alertsEnabled: false,
    tags: ["UP corridor"],
  },
  {
    id: "cor_06",
    name: "Mumbai–Goa",
    origin: "Mumbai",
    destination: "Goa",
    highway: "NH66",
    distanceKm: 590,
    riskLevel: "high",
    activeDisruptions: 1,
    lastChecked: iso(0.5),
    alertsEnabled: true,
    tags: ["Konkan coast", "Seasonal risk"],
  },
  {
    id: "cor_07",
    name: "Guwahati–Silchar",
    origin: "Guwahati",
    destination: "Silchar",
    highway: "NH37",
    distanceKm: 325,
    riskLevel: "high",
    activeDisruptions: 1,
    lastChecked: iso(0.3),
    alertsEnabled: true,
    tags: ["NE corridor", "Strike-prone"],
  },
  {
    id: "cor_08",
    name: "Delhi–Jaipur",
    origin: "Delhi",
    destination: "Jaipur",
    highway: "NH48",
    distanceKm: 280,
    riskLevel: "low",
    activeDisruptions: 1,
    lastChecked: iso(2),
    alertsEnabled: false,
    tags: ["Rajasthan route"],
  },
  {
    id: "cor_09",
    name: "Hyderabad–Bengaluru",
    origin: "Hyderabad",
    destination: "Bengaluru",
    highway: "NH44",
    distanceKm: 570,
    riskLevel: "safe",
    activeDisruptions: 0,
    lastChecked: iso(3),
    alertsEnabled: false,
    tags: ["South hub link"],
  },
];

// ── Pre-Planning — Calendar Events ───────────────────────────────

function calDate(daysFromToday: number): string {
  return new Date(Date.now() + daysFromToday * 86400000).toISOString().slice(0, 10);
}

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "cal_01",
    date: calDate(0),
    title: "Ganesh Chaturthi Immersion (Bengaluru)",
    category: "religious",
    region: "Bengaluru",
    states: ["Karnataka"],
    predictedRisk: "medium",
    affectedHighways: ["ORR", "Sarjapur Road", "Hosur Road"],
    description: "Annual Ganesh immersion processions through Bengaluru city. BBMP closes Outer Ring Road 19:00–23:00 IST. Traffic snarls expected from 17:00 IST.",
    isRecurring: true,
    recurrenceNote: "Annual — 10th day of Ganesh Chaturthi (Aug/Sep)",
  },
  {
    id: "cal_02",
    date: calDate(2),
    title: "Maharashtra Bandh — Labour Union Strike",
    category: "political",
    region: "Maharashtra",
    states: ["Maharashtra"],
    predictedRisk: "high",
    affectedHighways: ["NH48", "NH66", "NH160", "NH61"],
    description: "Central trade unions have called a 24h Maharashtra Bandh. Expected blockades on major highways entering Mumbai, Pune, and Nagpur.",
    isRecurring: false,
  },
  {
    id: "cal_03",
    date: calDate(4),
    title: "PM State Visit — Gujarat (Ahmedabad)",
    category: "vvip",
    region: "Gujarat",
    states: ["Gujarat"],
    predictedRisk: "high",
    affectedHighways: ["NH47", "NH48", "NH48A"],
    description: "Prime Minister's official visit to Ahmedabad. SPG will impose movement restrictions on major arterials 3h before and 2h after the event. Exact times TBD.",
    isRecurring: false,
  },
  {
    id: "cal_04",
    date: calDate(5),
    title: "Eid-ul-Milad-un-Nabi",
    category: "religious",
    region: "Pan-India",
    states: ["Maharashtra", "UP", "J&K", "West Bengal", "Kerala"],
    predictedRisk: "medium",
    affectedHighways: ["NH44", "NH19", "NH66"],
    description: "Public holiday. Processions in major cities. Traffic restrictions expected in old city areas of Mumbai, Lucknow, Hyderabad, and Kolkata.",
    isRecurring: true,
    recurrenceNote: "Annual Islamic calendar — date shifts ~11 days each year",
  },
  {
    id: "cal_05",
    date: calDate(7),
    title: "Monsoon Withdrawal — North India Fog Season Begins",
    category: "weather",
    region: "North India",
    states: ["Haryana", "UP", "Punjab", "Rajasthan"],
    predictedRisk: "medium",
    affectedHighways: ["NH44", "NH48", "Yamuna Expressway", "NH58"],
    description: "Post-monsoon fog season typically starts in late Oct/Nov. IMD forecasts early onset this year. Dense fog expected on Yamuna Expressway and NH44 Haryana stretch from early morning hours.",
    isRecurring: true,
    recurrenceNote: "Annual seasonal — Oct to Feb, worst Jan–Feb",
  },
  {
    id: "cal_06",
    date: calDate(10),
    title: "Farmer March — Delhi Singhu & Tikri Borders",
    category: "political",
    region: "Delhi–Haryana Border",
    states: ["Haryana", "Delhi"],
    predictedRisk: "high",
    affectedHighways: ["NH44", "NH9", "NH58"],
    description: "Farmers' union has announced a march to Delhi. Singhu and Tikri border entry points will likely be blocked. Police have deployed additional forces.",
    isRecurring: false,
  },
  {
    id: "cal_07",
    date: calDate(14),
    title: "Dussehra — Pan-India (High Traffic Day)",
    category: "religious",
    region: "Pan-India",
    states: ["All"],
    predictedRisk: "medium",
    affectedHighways: ["All major city access roads"],
    description: "Dussehra public holiday and evening Ravan dahan events. City arterial roads congested 17:00–21:00 IST. Long-haul inter-city routes unaffected.",
    isRecurring: true,
    recurrenceNote: "Annual — Ashwin Shukla Dashami (Oct)",
  },
  {
    id: "cal_08",
    date: calDate(18),
    title: "North East Monsoon — Coastal TN & AP Peak",
    category: "weather",
    region: "Coastal Tamil Nadu",
    states: ["Tamil Nadu", "Andhra Pradesh"],
    predictedRisk: "high",
    affectedHighways: ["NH16", "NH32", "NH716"],
    description: "IMD has forecast North East Monsoon peak rainfall for coastal TN and south AP. Flooding likely on NH16 near Nellore and NH716 near Tirupati approach roads.",
    isRecurring: true,
    recurrenceNote: "Annual — Oct to Dec, Northeast Monsoon season",
  },
  {
    id: "cal_09",
    date: calDate(21),
    title: "Diwali — National Holiday (Supply Chain Surge)",
    category: "religious",
    region: "Pan-India",
    states: ["All"],
    predictedRisk: "medium",
    affectedHighways: ["All corridors"],
    description: "Diwali weekend causes extreme surge in freight volumes. Truck availability drops 40%. Pre-book transport 2 weeks ahead. Last-mile deliveries in cities severely congested.",
    isRecurring: true,
    recurrenceNote: "Annual — Kartik Amavasya (Oct/Nov)",
  },
  {
    id: "cal_10",
    date: calDate(25),
    title: "State Elections — Rajasthan Polling Day",
    category: "political",
    region: "Rajasthan",
    states: ["Rajasthan"],
    predictedRisk: "medium",
    affectedHighways: ["NH48", "NH58", "NH12"],
    description: "Rajasthan assembly elections. Dry day declared. Commercial vehicle movement restrictions in polling districts from 06:00–18:00 IST. Security checkpoints on all state highways.",
    isRecurring: false,
  },
  {
    id: "cal_11",
    date: calDate(30),
    title: "Chhath Puja — Bihar & Eastern UP River Ghats",
    category: "religious",
    region: "Bihar / Eastern UP",
    states: ["Bihar", "UP", "Jharkhand"],
    predictedRisk: "medium",
    affectedHighways: ["NH19", "NH30", "NH27"],
    description: "Chhath Puja processions to river ghats. NH19 near Patna and NH30 near Ara expected to see heavy pilgrim movement. City access roads blocked 05:00–08:00 and 17:00–20:00 IST.",
    isRecurring: true,
    recurrenceNote: "Annual — Kartik Shukla Shashthi (Oct/Nov)",
  },
  {
    id: "cal_12",
    date: calDate(-2),
    title: "Bharat Bandh — NH44 blockade (Active)",
    category: "political",
    region: "Pan-India",
    states: ["Haryana", "Punjab", "UP"],
    predictedRisk: "critical",
    affectedHighways: ["NH44"],
    description: "Active bandh. NH44 blocked at Panipat, Karnal, and Shambhu border. Expected to lift by evening.",
    isRecurring: false,
  },
];

// ── Advisory Platform — Trip Monitoring Mock Data ────────────────────────────
// Realistic Bengal/NE India truck route data used when TRIP_SOURCE=mock.

export interface AdvTripRow {
  id: string;
  origin_name: string;
  destination_name: string;
  truck_reg: string | null;
  driver_name: string | null;
  cargo_type: string | null;
  scheduled_at: string | null;
  status: string;
  notes: string | null;
  route_count: number;
  alert_count: number;
  created_at: string;
}

export interface AdvRouteRow {
  id: string;
  trip_id: string;
  label: string;
  summary: string | null;
  distance_km: string | null;
  duration_hours: string | null;
  is_primary: boolean;
  risk_level: string;
}

export interface AdvSegmentRow {
  id: string;
  route_id: string;
  segment_type: "district" | "tehsil" | "national_highway" | "state_highway";
  name: string;
  state: string | null;
  seq: number;
}

export interface AdvAlertRow {
  id: string;
  trip_id: string;
  matched_segment: string | null;
  severity: string;
  message: string;
  status: string;
  category: string;
  risk_level: string;
  eta_impact_hours: string;
  confidence: number;
  created_at: string;
}

const advNow = new Date();
const advHoursAgo = (h: number) => new Date(advNow.getTime() - h * 3_600_000).toISOString();
const advHoursFromNow = (h: number) => new Date(advNow.getTime() + h * 3_600_000).toISOString();

// ── Segments ─────────────────────────────────────────────────────
export const MOCK_ADV_SEGMENTS: AdvSegmentRow[] = [
  // Route 1a — Kolkata → Siliguri via NH12 (primary)
  { id: "seg_1a_1",  route_id: "rt_01a", segment_type: "national_highway", name: "NH12",        state: "West Bengal",      seq: 0 },
  { id: "seg_1a_2",  route_id: "rt_01a", segment_type: "national_highway", name: "NH27",        state: "West Bengal",      seq: 1 },
  { id: "seg_1a_3",  route_id: "rt_01a", segment_type: "district",         name: "Bardhaman",   state: "West Bengal",      seq: 2 },
  { id: "seg_1a_4",  route_id: "rt_01a", segment_type: "district",         name: "Murshidabad", state: "West Bengal",      seq: 3 },
  { id: "seg_1a_5",  route_id: "rt_01a", segment_type: "district",         name: "Malda",       state: "West Bengal",      seq: 4 },
  { id: "seg_1a_6",  route_id: "rt_01a", segment_type: "district",         name: "Uttar Dinajpur", state: "West Bengal",   seq: 5 },
  { id: "seg_1a_7",  route_id: "rt_01a", segment_type: "district",         name: "Jalpaiguri",  state: "West Bengal",      seq: 6 },
  { id: "seg_1a_8",  route_id: "rt_01a", segment_type: "tehsil",           name: "Katwa",       state: "West Bengal",      seq: 7 },
  { id: "seg_1a_9",  route_id: "rt_01a", segment_type: "tehsil",           name: "Lalbagh",     state: "West Bengal",      seq: 8 },
  { id: "seg_1a_10", route_id: "rt_01a", segment_type: "tehsil",           name: "English Bazar", state: "West Bengal",    seq: 9 },
  { id: "seg_1a_11", route_id: "rt_01a", segment_type: "tehsil",           name: "Dalkhola",    state: "West Bengal",      seq: 10 },
  { id: "seg_1a_12", route_id: "rt_01a", segment_type: "tehsil",           name: "Jalpaiguri Sadar", state: "West Bengal", seq: 11 },

  // Route 1b — Kolkata → Siliguri via NH19 bypass (alternate)
  { id: "seg_1b_1",  route_id: "rt_01b", segment_type: "national_highway", name: "NH19",        state: "West Bengal",      seq: 0 },
  { id: "seg_1b_2",  route_id: "rt_01b", segment_type: "national_highway", name: "NH12",        state: "West Bengal",      seq: 1 },
  { id: "seg_1b_3",  route_id: "rt_01b", segment_type: "national_highway", name: "NH27",        state: "West Bengal",      seq: 2 },
  { id: "seg_1b_4",  route_id: "rt_01b", segment_type: "district",         name: "Howrah",      state: "West Bengal",      seq: 3 },
  { id: "seg_1b_5",  route_id: "rt_01b", segment_type: "district",         name: "Hooghly",     state: "West Bengal",      seq: 4 },
  { id: "seg_1b_6",  route_id: "rt_01b", segment_type: "district",         name: "Malda",       state: "West Bengal",      seq: 5 },
  { id: "seg_1b_7",  route_id: "rt_01b", segment_type: "district",         name: "Jalpaiguri",  state: "West Bengal",      seq: 6 },
  { id: "seg_1b_8",  route_id: "rt_01b", segment_type: "tehsil",           name: "Uluberia",    state: "West Bengal",      seq: 7 },
  { id: "seg_1b_9",  route_id: "rt_01b", segment_type: "tehsil",           name: "Pandua",      state: "West Bengal",      seq: 8 },
  { id: "seg_1b_10", route_id: "rt_01b", segment_type: "tehsil",           name: "Dalkhola",    state: "West Bengal",      seq: 9 },

  // Route 2a — Kolkata → Bagdogra (single route via NH12)
  { id: "seg_2a_1",  route_id: "rt_02a", segment_type: "national_highway", name: "NH12",        state: "West Bengal",      seq: 0 },
  { id: "seg_2a_2",  route_id: "rt_02a", segment_type: "national_highway", name: "NH27",        state: "West Bengal",      seq: 1 },
  { id: "seg_2a_3",  route_id: "rt_02a", segment_type: "district",         name: "Bardhaman",   state: "West Bengal",      seq: 2 },
  { id: "seg_2a_4",  route_id: "rt_02a", segment_type: "district",         name: "Murshidabad", state: "West Bengal",      seq: 3 },
  { id: "seg_2a_5",  route_id: "rt_02a", segment_type: "district",         name: "Malda",       state: "West Bengal",      seq: 4 },
  { id: "seg_2a_6",  route_id: "rt_02a", segment_type: "district",         name: "Darjeeling",  state: "West Bengal",      seq: 5 },
  { id: "seg_2a_7",  route_id: "rt_02a", segment_type: "tehsil",           name: "Siliguri",    state: "West Bengal",      seq: 6 },
  { id: "seg_2a_8",  route_id: "rt_02a", segment_type: "tehsil",           name: "Phansidewa",  state: "West Bengal",      seq: 7 },

  // Route 3a — Haldia → Patna via NH16 + NH19 (primary)
  { id: "seg_3a_1",  route_id: "rt_03a", segment_type: "national_highway", name: "NH16",        state: "West Bengal",      seq: 0 },
  { id: "seg_3a_2",  route_id: "rt_03a", segment_type: "national_highway", name: "NH19",        state: "Jharkhand",        seq: 1 },
  { id: "seg_3a_3",  route_id: "rt_03a", segment_type: "district",         name: "East Midnapore", state: "West Bengal",   seq: 2 },
  { id: "seg_3a_4",  route_id: "rt_03a", segment_type: "district",         name: "West Midnapore", state: "West Bengal",   seq: 3 },
  { id: "seg_3a_5",  route_id: "rt_03a", segment_type: "district",         name: "Jharkhand Corridor", state: "Jharkhand", seq: 4 },
  { id: "seg_3a_6",  route_id: "rt_03a", segment_type: "district",         name: "Patna",       state: "Bihar",            seq: 5 },
  { id: "seg_3a_7",  route_id: "rt_03a", segment_type: "tehsil",           name: "Haldia",      state: "West Bengal",      seq: 6 },
  { id: "seg_3a_8",  route_id: "rt_03a", segment_type: "tehsil",           name: "Kharagpur",   state: "West Bengal",      seq: 7 },

  // Route 5a — Durgapur → Kolkata via NH19
  { id: "seg_5a_1",  route_id: "rt_05a", segment_type: "national_highway", name: "NH19",        state: "West Bengal",      seq: 0 },
  { id: "seg_5a_2",  route_id: "rt_05a", segment_type: "district",         name: "Paschim Bardhaman", state: "West Bengal", seq: 1 },
  { id: "seg_5a_3",  route_id: "rt_05a", segment_type: "district",         name: "Purba Bardhaman", state: "West Bengal",  seq: 2 },
  { id: "seg_5a_4",  route_id: "rt_05a", segment_type: "district",         name: "Hooghly",     state: "West Bengal",      seq: 3 },
  { id: "seg_5a_5",  route_id: "rt_05a", segment_type: "tehsil",           name: "Durgapur",    state: "West Bengal",      seq: 4 },
  { id: "seg_5a_6",  route_id: "rt_05a", segment_type: "tehsil",           name: "Burdwan",     state: "West Bengal",      seq: 5 },
  { id: "seg_5a_7",  route_id: "rt_05a", segment_type: "tehsil",           name: "Singur",      state: "West Bengal",      seq: 6 },
];

// ── Routes ───────────────────────────────────────────────────────
export const MOCK_ADV_ROUTES: AdvRouteRow[] = [
  { id: "rt_01a", trip_id: "adv_t01", label: "Route 1", summary: "NH12 → Bardhaman → Malda → NH27", distance_km: "516", duration_hours: "9.5",  is_primary: true,  risk_level: "high" },
  { id: "rt_01b", trip_id: "adv_t01", label: "Route 2", summary: "NH19 → Howrah bypass → Dalkhola → NH27", distance_km: "541", duration_hours: "10.2", is_primary: false, risk_level: "medium" },
  { id: "rt_02a", trip_id: "adv_t02", label: "Route 1", summary: "NH12 → Bardhaman → Malda → NH27 → Bagdogra", distance_km: "524", duration_hours: "9.8",  is_primary: true,  risk_level: "high" },
  { id: "rt_03a", trip_id: "adv_t03", label: "Route 1", summary: "NH16 → Kharagpur → NH19 → Patna", distance_km: "612", duration_hours: "11.0", is_primary: true,  risk_level: "low" },
  { id: "rt_05a", trip_id: "adv_t05", label: "Route 1", summary: "NH19 → Burdwan → Hooghly → Kolkata", distance_km: "174", duration_hours: "3.2",  is_primary: true,  risk_level: "low" },
];

// ── Alerts ───────────────────────────────────────────────────────
export const MOCK_ADV_ALERTS: AdvAlertRow[] = [
  {
    id: "adv_al_01",
    trip_id: "adv_t01",
    matched_segment: "Katwa, West Bengal",
    severity: "critical",
    message: "NH12 blocked near Katwa — farmers' agitation. Police lathi charge reported; all lanes stopped. Expect 4–6 hour delay or reroute via NH19.",
    status: "open",
    category: "political",
    risk_level: "critical",
    eta_impact_hours: "5",
    confidence: 92,
    created_at: advHoursAgo(1.5),
  },
  {
    id: "adv_al_02",
    trip_id: "adv_t01",
    matched_segment: "Murshidabad, West Bengal",
    severity: "warning",
    message: "IMD flood alert active for Murshidabad district. NH12 near Lalbagh may experience road submersion within 12 hours. Monitor closely.",
    status: "open",
    category: "weather",
    risk_level: "high",
    eta_impact_hours: "2",
    confidence: 76,
    created_at: advHoursAgo(3),
  },
  {
    id: "adv_al_03",
    trip_id: "adv_t01",
    matched_segment: "NH27",
    severity: "info",
    message: "Night driving restriction on NH27 near Siliguri between 22:00–06:00 IST per district administration order. Coordinate departure timing.",
    status: "open",
    category: "traffic",
    risk_level: "medium",
    eta_impact_hours: "1",
    confidence: 88,
    created_at: advHoursAgo(5),
  },
  {
    id: "adv_al_04",
    trip_id: "adv_t02",
    matched_segment: "Murshidabad, West Bengal",
    severity: "warning",
    message: "Same IMD flood advisory applies to this route. NH12 near Lalbagh at risk. Consider delaying departure by 24 hours pending flood update.",
    status: "open",
    category: "weather",
    risk_level: "high",
    eta_impact_hours: "2",
    confidence: 76,
    created_at: advHoursAgo(3),
  },
];

// ── Trips list ────────────────────────────────────────────────────
export const MOCK_ADV_TRIPS: AdvTripRow[] = [
  {
    id: "adv_t01",
    origin_name: "Kolkata",
    destination_name: "Siliguri",
    truck_reg: "WB 14 AB 5521",
    driver_name: "Sunil Mahato",
    cargo_type: "FMCG — Cigarettes & Tobacco",
    scheduled_at: advHoursFromNow(6),
    status: "monitoring",
    notes: "Priority shipment for NE region. Avoid night halt in Malda.",
    route_count: 2,
    alert_count: 3,
    created_at: advHoursAgo(24),
  },
  {
    id: "adv_t02",
    origin_name: "Kolkata",
    destination_name: "Bagdogra",
    truck_reg: "WB 14 CD 7733",
    driver_name: "Rahim Ali",
    cargo_type: "FMCG — Packaged Foods",
    scheduled_at: advHoursFromNow(10),
    status: "monitoring",
    notes: null,
    route_count: 1,
    alert_count: 1,
    created_at: advHoursAgo(18),
  },
  {
    id: "adv_t03",
    origin_name: "Haldia",
    destination_name: "Patna",
    truck_reg: "WB 06 GH 2210",
    driver_name: "Deepak Oraon",
    cargo_type: "Industrial — Steel Coils",
    scheduled_at: advHoursFromNow(14),
    status: "monitoring",
    notes: "Overweight permit required at JH border check-post.",
    route_count: 1,
    alert_count: 0,
    created_at: advHoursAgo(12),
  },
  {
    id: "adv_t04",
    origin_name: "Kolkata",
    destination_name: "Guwahati",
    truck_reg: null,
    driver_name: null,
    cargo_type: "FMCG — Personal Care",
    scheduled_at: advHoursFromNow(36),
    status: "planned",
    notes: "Truck assignment pending. NH27 long-haul — consider driver change at Siliguri.",
    route_count: 0,
    alert_count: 0,
    created_at: advHoursAgo(6),
  },
  {
    id: "adv_t05",
    origin_name: "Durgapur",
    destination_name: "Kolkata",
    truck_reg: "WB 40 JK 9988",
    driver_name: "Ramakanta Tudu",
    cargo_type: "FMCG — Beverages",
    scheduled_at: advHoursAgo(2),
    status: "dispatched",
    notes: null,
    route_count: 1,
    alert_count: 0,
    created_at: advHoursAgo(48),
  },
];
